import ast
import csv
import json
import os
import re
import subprocess
from collections import defaultdict
from datetime import datetime
from pathlib import Path

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.formatting.rule import FormulaRule
from openpyxl.utils import get_column_letter


ROOT = Path(__file__).resolve().parents[1]
OUT_XLSX = ROOT / "cfl_data_model_inventory.xlsx"
OUT_CSV_DIR = ROOT / "data_model_inventory_csv"

ENTITY_HEADERS = [
    "Entity",
    "Field Name",
    "Display Label",
    "Data Type",
    "Example Value",
    "Source Status",
    "Source File",
    "Source Line / Location",
    "Required?",
    "Nullable?",
    "Default Value",
    "Enum / Allowed Values",
    "Current Usage",
    "Used On Screens",
    "Editable By User?",
    "Dynamic / Computed?",
    "Persistence Needed?",
    "Notes",
    "Recommendation",
    "Approval Status",
]

TRAIT_HEADERS = [
    "Trait Name",
    "Category",
    "Description",
    "Positive / Negative / Mixed",
    "Affects Simulation?",
    "Affects Recruiting?",
    "Affects Development?",
    "Affects Morale?",
    "Example Impact",
    "Source Status",
    "Source File",
    "Source Line / Location",
    "Approval Status",
]

ENTITY_INDEX_HEADERS = [
    "Entity Name",
    "Description",
    "Source Status",
    "Primary Source File",
    "Approx Field Count",
    "Related Screens",
    "Related Entities",
    "Notes",
    "Approval Status",
]

UI_HEADERS = [
    "Screen Name",
    "Section / Component",
    "Entity",
    "Field Name",
    "Display Label",
    "Required On Screen?",
    "Optional?",
    "Editable?",
    "Sortable?",
    "Filterable?",
    "Visible By Default?",
    "Detail Only?",
    "Notes",
    "Approval Status",
]

ENUM_HEADERS = [
    "Value List",
    "Value",
    "Source Status",
    "Source File",
    "Source Line / Location",
    "Used By Entity",
    "Notes",
    "Approval Status",
]

MISSING_HEADERS = [
    "Issue",
    "Entity",
    "Field",
    "Source File",
    "Why It Matters",
    "Suggested Resolution",
    "Priority",
    "Approval Status",
]

RECOMMENDED_HEADERS = [
    "Entity",
    "Recommended Field",
    "Data Type",
    "Why Needed",
    "Screen Usage",
    "Simulation Usage",
    "Priority",
    "Approval Status",
]

CHANGE_HEADERS = ["date", "action", "notes", "generated by", "repo commit hash if available"]

SHEETS = [
    "README",
    "Entity Index",
    "Player Fields",
    "Player Ratings",
    "Player Traits",
    "Player Development",
    "Recruit Fields",
    "Coach Fields",
    "Staff Fields",
    "Team Fields",
    "Program Fields",
    "School Brand Fields",
    "Stadium Fields",
    "Uniform Fields",
    "NIL Fields",
    "Game Fields",
    "Schedule Fields",
    "Conference Fields",
    "Ranking Fields",
    "News Event Fields",
    "Simulation Fields",
    "Playbook - Scheme Fields",
    "UI Display Mapping",
    "Enums & Value Lists",
    "Missing - Ambiguous Fields",
    "Recommended Additions",
    "Change Log",
]

SOURCE_STATUS_VALUES = [
    "existing-code",
    "mock-only",
    "spec-only",
    "inferred",
    "missing-but-needed",
    "duplicate/unclear",
]

STATUS_COLORS = {
    "existing-code": "C6EFCE",
    "mock-only": "BDD7EE",
    "spec-only": "D9EAD3",
    "inferred": "FFF2CC",
    "missing-but-needed": "FCE4D6",
    "duplicate/unclear": "F4CCCC",
    "pending-review": "FFF2CC",
    "approved": "C6EFCE",
    "rejected": "F4CCCC",
    "revise": "FCE4D6",
}

TAB_TO_ENTITY = {
    "Player Fields": "Player",
    "Player Ratings": "Player Rating",
    "Player Development": "Player Development",
    "Recruit Fields": "Recruit",
    "Coach Fields": "Coach",
    "Staff Fields": "Staff",
    "Team Fields": "Team",
    "Program Fields": "Program",
    "School Brand Fields": "School Brand",
    "Stadium Fields": "Stadium",
    "Uniform Fields": "Uniform",
    "NIL Fields": "NIL",
    "Game Fields": "Game",
    "Schedule Fields": "Schedule",
    "Conference Fields": "Conference",
    "Ranking Fields": "Ranking",
    "News Event Fields": "News Event",
    "Simulation Fields": "Simulation",
    "Playbook - Scheme Fields": "Playbook / Scheme",
}

CANONICAL = {
    "Player Fields": [
        "id", "first name", "last name", "full name", "name", "type", "position", "archetype",
        "jersey number", "height", "weight", "year/class", "classYear", "age", "hometown",
        "state", "high school", "handedness", "eligibility", "redshirt status", "transfer status",
        "NIL status", "morale", "confidence", "fatigue", "injury status", "status",
        "depth chart role", "captain status", "promises", "personality", "leadership",
        "work ethic", "discipline", "academics", "overall", "potential", "development speed",
        "developmentFocus", "scheme fit", "playing time expectation", "teamId", "attrs",
    ],
    "Player Ratings": [
        "throwing", "decisions", "anticipation", "composure", "concentration", "technique", "vision",
        "ballCarrying", "catching", "routeRunning", "firstTouch", "passBlocking", "runBlocking",
        "passRush", "tackling", "coverage", "strength", "positioning", "determination", "aggression",
        "jumping", "stamina", "pace", "acceleration", "agility", "balance", "injuryProneness",
        "consistency", "importantGames", "workRate", "teamwork", "bravery", "leadership",
        "adaptability", "professionalism", "sportsmanship",
        "arm strength", "short accuracy", "intermediate accuracy", "deep accuracy", "timing",
        "pocket movement", "pressure response", "pre-snap ID", "post-snap processing", "RPO read",
        "option mesh", "progression discipline", "scramble instinct", "ball security", "burst",
        "top speed", "contact balance", "power", "patience", "one-cut ability", "gap discipline",
        "receiving", "release", "leverage understanding", "hands", "contested catch", "YAC",
        "blocking", "option-route intelligence", "vertical speed", "spacing discipline",
        "red zone feel", "run block power", "zone footwork", "combo timing", "reach block",
        "pull ability", "pass set", "anchor", "blitz pickup", "stunt recognition",
        "communication", "penalty discipline", "get-off", "bend", "hand usage",
        "block destruction", "pass rush plan", "contain discipline", "motor", "run fit strength",
        "run fit", "block shed", "pursuit angle", "zone drop", "man coverage", "blitz timing",
        "play recognition", "eye discipline", "RPO discipline", "zone coverage", "match coverage",
        "press", "off technique", "ball skills", "run support", "route recognition", "recovery speed",
        "kick power", "kick accuracy", "punt power", "punt accuracy", "long snapping",
        "return vision", "return ball security",
    ],
    "Player Development": [
        "developmentFocus", "potential", "development speed", "work ethic", "practice habits",
        "coachability", "learning speed", "training load", "redshirt plan", "fatigue",
        "injuryProneness", "consistency", "importantGames", "professionalism", "determination",
    ],
    "Recruit Fields": [
        "id", "name", "position", "stars", "rank", "state", "hometown", "high school", "interest",
        "status", "visit", "pipeline", "scholarship", "offer amount", "NIL demand", "commitment",
        "academics", "personality", "scheme fit", "scouting grade", "potential",
    ],
    "Coach Fields": [
        "id", "name", "age", "role", "position group", "scheme preference", "offensive philosophy",
        "defensive philosophy", "recruiting ability", "player development", "play calling",
        "leadership", "motivation", "discipline", "adaptability", "scouting", "NIL influence",
        "pipeline strength", "prestige", "loyalty", "ambition", "contract years", "salary",
        "buyout", "previous schools", "coaching tree", "personality", "traits",
        "tacticalKnowledge", "offensiveStrategy", "defensiveStrategy", "qbDevelopment",
        "skillDevelopment", "lineDevelopment", "strengthConditioning", "specialTeams",
        "gameManagement", "inGameAdaptation", "opponentAnalysis", "dataAnalysis",
        "recruitment", "scoutingCurrent", "scoutingPotential", "negotiating", "budgetControl",
        "mediaHandling", "manManagement", "determination", "professionalism", "decisionMaking",
        "composure", "pressureHandling", "teaching", "sportsScience", "academyDevelopment",
        "staffDelegation",
    ],
    "Staff Fields": [
        "recruiting coordinator", "strength coach", "trainer", "academic advisor", "NIL director",
        "scout", "analyst", "coordinator", "position coach", "operations director", "confidence",
        "notes", "role", "department", "status",
    ],
    "Team Fields": [
        "team id", "id", "school id", "school name", "name", "shortName", "nickname",
        "abbreviation", "crest", "conference", "division", "logo", "colors", "record",
        "conference record", "ranking", "prestige", "overall rating", "offense rating",
        "defense rating", "special teams rating", "morale", "chemistry", "fan support",
        "facilities grade", "academic grade", "NIL collective grade", "recruiting class rank",
        "roster size", "scholarships available", "playbook", "offensive scheme", "defensive scheme",
        "rivalries", "rival", "programRating", "historicalRatings", "projectedRatings",
    ],
    "Program Fields": [
        "id", "name", "shortName", "crest", "record", "rival", "headCoachProfileId",
        "schoolProfileId", "stadiumProfileId", "basePrestige", "baseFanConfidence",
        "baseDonorConfidence", "baseAcademicStability", "program prestige", "coach trust",
        "booster support", "fan confidence", "athletic budget", "recruiting budget", "NIL budget",
        "facilities level", "stadium level", "academic reputation", "brand exposure",
        "pipeline states", "historical wins", "championships", "bowl history", "rivalry records",
        "media expectations", "playoff expectations", "wins", "losses", "historicalRecords",
    ],
    "School Brand Fields": [
        "id", "schoolName", "nickname", "abbreviation", "conference", "primaryColor",
        "secondaryColor", "accentColor", "darkNeutral", "lightNeutral", "logos", "primary",
        "alternate", "wordmark", "helmet", "field", "scoreboard", "gradients",
        "headerStart", "headerEnd", "buttonStart", "buttonEnd", "school name", "mascot",
        "mascot type", "primary logo", "alternate logo", "helmet decal", "field logo",
        "jersey wordmark", "scoreboard logo", "number font", "stripe pattern",
    ],
    "Stadium Fields": [
        "id", "stadium name", "name", "capacity", "current capacity", "target capacity",
        "year built", "last renovation", "field type", "surface quality", "fan experience",
        "home field advantage", "noise rating", "seating tiers", "club seats", "suites",
        "scoreboard type", "atmosphere rating", "expansion options", "upgrade costs",
        "upgrade completion date", "atmosphere", "turfQuality", "weatherControl",
        "lockerRoomQuality", "trainingComplexLink", "medicalBayQuality", "crowdNoise",
        "sightlines", "pressFacilities", "vipSuites", "concessionQuality", "parkingAccess",
        "transitAccess", "securityReadiness", "homeFieldAdvantage", "scoreboardTech",
        "broadcastInfrastructure", "lightingQuality", "drainageQuality", "structuralCondition",
        "expansionPotential", "maintenanceDiscipline", "emergencyPreparedness", "acoustics",
        "studentSectionEnergy", "accessibility", "familyAmenities", "fieldHeating",
        "practiceFieldAdjacency", "travelTeamFacilities", "officialsFacilities", "replaySupport",
        "sustainability", "revenueEfficiency",
    ],
    "Uniform Fields": [
        "uniform set name", "helmet model", "helmet shell color", "facemask color", "stripe style",
        "stripe color", "decals", "jersey base color", "jersey number color", "wordmark",
        "sleeve stripe", "pants color", "pants stripe", "socks color", "gloves color",
        "cleats color", "home/away/alternate/rivalry designation",
    ],
    "NIL Fields": [
        "NIL budget total", "spent", "committed", "available", "monthly income",
        "monthly expenses", "collective name", "donor influence", "partner list",
        "player NIL value", "recruit NIL demand", "offer amount", "risk", "activity",
        "brand health", "social following", "engagement", "top earners", "nilCapacity",
        "nilStructure",
    ],
    "Game Fields": [
        "game id", "id", "week", "date", "season", "home team", "away team", "neutral site",
        "stadium", "weather", "kickoff time", "TV/network", "spread", "final score",
        "quarter scores", "status", "rivalry", "bowl/playoff flag", "homeScore", "awayScore",
        "ourScore", "oppScore", "drives", "events", "playByPlay", "summary",
    ],
    "Schedule Fields": [
        "schedule id", "team id", "season", "week", "opponent", "home/away/neutral",
        "result", "score", "date", "time", "conference game", "rivalry game",
        "ranked opponent", "TV", "stadium", "dateLabel", "weekLabel", "nextEvent",
        "agenda", "notifications", "linkedRoute",
    ],
    "Conference Fields": [
        "id", "name", "short", "tier", "members", "conference", "division", "minConfSize",
        "maxMovesPerCycle", "fromConf", "toConf", "programId",
    ],
    "Ranking Fields": [
        "rank", "ranking", "teamGrade", "wins", "losses", "record", "strengthOfSchedule",
        "conference", "prestige", "fanBaseScore", "award", "ballots",
    ],
    "News Event Fields": [
        "id", "title", "body", "severity", "department", "deadline", "linked", "targetView",
        "blocking", "resolved", "summary", "at", "type", "status", "message",
    ],
    "Simulation Fields": [
        "play id", "drive id", "down", "distance", "field position", "hash", "clock", "quarter",
        "score state", "personnel", "formation", "motion", "offensive concept",
        "defensive front", "coverage", "pressure", "box count", "read defender",
        "primary conflict", "success probability", "explosive probability", "turnover probability",
        "sack probability", "penalty probability", "play result", "yards gained",
        "responsible players", "explanation note", "playId", "driveIndex", "yardsGained",
        "playType", "result", "players", "possessionTeamId", "scoring", "turnover", "seed",
        "gameIndex", "homeTendencies", "awayTendencies", "homeGamePlan", "awayGamePlan",
        "passRate", "runRate", "blitzRate", "pace", "tacticalProfile", "injuryCadencePercent",
    ],
    "Playbook - Scheme Fields": [
        "offensive scheme", "defensive scheme", "personnel grouping", "formation", "concept",
        "play tag", "run/pass/RPO/play-action/screen", "strengths", "weaknesses",
        "required skills", "stressed defenders", "vulnerable to", "counters",
        "situation preferences", "red zone suitability", "short-yardage suitability",
        "explosive potential", "risk level", "aggressive", "tempo",
    ],
}

RECOMMENDED_TRAITS = [
    ("clutch", "Mental", "Improves execution in high-leverage moments.", "Positive", "Yes", "No", "No", "Yes", "Higher late-game composure."),
    ("volatile confidence", "Mental", "Performance swings sharply after success or failure.", "Mixed", "Yes", "No", "Yes", "Yes", "Can snowball hot or cold stretches."),
    ("film junkie", "Development", "Extra preparation improves recognition and learning.", "Positive", "Yes", "Yes", "Yes", "No", "Faster processing growth."),
    ("poor practice habits", "Development", "Practice quality limits improvement.", "Negative", "No", "No", "Yes", "Yes", "Lower weekly development."),
    ("high football IQ", "Mental", "Reads leverage, rotations, and assignments quickly.", "Positive", "Yes", "Yes", "Yes", "No", "Better assignment execution."),
    ("raw athlete", "Development", "High tools with slower skill polish.", "Mixed", "Yes", "Yes", "Yes", "No", "High ceiling, early mistakes."),
    ("injury prone", "Medical", "Elevated injury risk.", "Negative", "Yes", "No", "Yes", "Yes", "Higher missed-time probability."),
    ("locker room leader", "Leadership", "Improves morale and chemistry.", "Positive", "No", "No", "No", "Yes", "Raises unit morale."),
    ("transfer risk", "Roster", "More likely to leave after unmet expectations.", "Negative", "No", "Yes", "No", "Yes", "Requires playing-time management."),
    ("NIL-driven", "Recruiting", "Responds strongly to NIL offers.", "Mixed", "No", "Yes", "No", "Yes", "Higher NIL sensitivity."),
    ("loyal", "Roster", "Less likely to transfer or decommit.", "Positive", "No", "Yes", "No", "Yes", "Retains through adversity."),
    ("competitor", "Mental", "Responds well to depth chart pressure.", "Positive", "Yes", "Yes", "Yes", "Yes", "Better battle outcomes."),
    ("poor discipline", "Mental", "Penalty and off-field risk.", "Negative", "Yes", "Yes", "No", "Yes", "Higher penalty/risk events."),
    ("high motor", "Physical/Mental", "Sustains effort through play and game.", "Positive", "Yes", "Yes", "Yes", "No", "Better pursuit and finish."),
    ("coachable", "Development", "Gets more from staff feedback.", "Positive", "No", "Yes", "Yes", "No", "Higher development multiplier."),
    ("slow learner", "Development", "Slower scheme and skill absorption.", "Negative", "Yes", "No", "Yes", "No", "Limits complex-role growth."),
    ("big game performer", "Mental", "Raises floor in rivalry, ranked, and postseason games.", "Positive", "Yes", "Yes", "No", "Yes", "Improves important-game output."),
]

SCREEN_FIELD_HINTS = {
    "Dashboard": [("Program", "name"), ("Program", "record"), ("Ranking", "rank"), ("Team", "overall rating"), ("Schedule", "opponent"), ("News Event", "title")],
    "Team Hub": [("Program", "name"), ("Team", "record"), ("Team", "offense rating"), ("Team", "defense rating"), ("Team", "special teams rating")],
    "Roster": [("Player", "name"), ("Player", "position"), ("Player", "classYear"), ("Player", "overall"), ("Player", "potential"), ("Player", "morale"), ("Player", "status")],
    "Player Profile": [("Player", "name"), ("Player", "position"), ("Player", "developmentFocus"), ("Player", "morale"), ("Player Rating", "attrs")],
    "Depth Chart": [("Player", "position"), ("Player", "depth chart role"), ("Player", "overall"), ("Player", "fatigue"), ("Player", "injury status")],
    "Recruiting Board": [("Recruit", "name"), ("Recruit", "position"), ("Recruit", "stars"), ("Recruit", "interest"), ("Recruit", "status")],
    "Prospect Detail": [("Recruit", "name"), ("Recruit", "scheme fit"), ("Recruit", "NIL demand"), ("Recruit", "visit"), ("Recruit", "scouting grade")],
    "NIL Budget": [("NIL", "NIL budget total"), ("NIL", "spent"), ("NIL", "committed"), ("NIL", "available")],
    "NIL Management": [("NIL", "player NIL value"), ("NIL", "recruit NIL demand"), ("NIL", "offer amount"), ("NIL", "risk")],
    "Coach Profile": [("Coach", "name"), ("Coach", "role"), ("Coach", "offensive philosophy"), ("Coach", "defensive philosophy"), ("Coach", "traits")],
    "Staff Management": [("Staff", "role"), ("Staff", "confidence"), ("Staff", "notes")],
    "Stadium Builder": [("Stadium", "capacity"), ("Stadium", "expansion options"), ("Stadium", "upgrade costs"), ("Stadium", "homeFieldAdvantage")],
    "Uniform Creator": [("Uniform", "helmet shell color"), ("Uniform", "jersey base color"), ("Uniform", "pants color"), ("Uniform", "stripe style")],
    "School Creator": [("School Brand", "schoolName"), ("School Brand", "nickname"), ("School Brand", "primaryColor"), ("School Brand", "secondaryColor")],
    "Game Planning": [("Playbook / Scheme", "offensive scheme"), ("Playbook / Scheme", "defensive scheme"), ("Simulation", "passRate"), ("Simulation", "blitzRate")],
    "Scouting Report": [("Coach", "opponentAnalysis"), ("Simulation", "personnel"), ("Simulation", "formation"), ("Simulation", "coverage")],
    "Schedule": [("Schedule", "week"), ("Schedule", "opponent"), ("Schedule", "date"), ("Schedule", "status")],
    "Rankings": [("Ranking", "rank"), ("Ranking", "record"), ("Ranking", "conference")],
    "Game Report Card": [("Game", "final score"), ("Game", "summary"), ("Simulation", "yards gained"), ("Simulation", "turnover probability")],
    "Postgame Box Score": [("Game", "homeScore"), ("Game", "awayScore"), ("Game", "quarter scores"), ("Simulation", "players")],
    "Skill Tree / Coaching Upgrades": [("Coach", "player development"), ("Coach", "recruiting ability"), ("Coach", "play calling")],
}


def rel(path):
    try:
        return str(Path(path).resolve().relative_to(ROOT)).replace("\\", "/")
    except Exception:
        return str(path).replace("\\", "/")


def display_label(field):
    text = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", str(field)).replace("_", " ").replace("-", " ")
    return " ".join(text.split()).title()


def infer_type(value):
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    if value is None:
        return "null"
    if isinstance(value, str):
        if re.match(r"^#[0-9A-Fa-f]{6}$", value):
            return "color/string"
        if re.match(r"^\d{4}-\d{2}-\d{2}", value):
            return "date/string"
        return "string"
    return type(value).__name__


def source_status(path):
    p = rel(path)
    if p.startswith(("data/", "game_data/", "data_raw/", "data_processed/", "harness/runs/")):
        return "mock-only"
    if p.startswith(("docs/", "ai-pack/", "cfl_agent_repo_pack/")):
        return "spec-only"
    if p.endswith((".md", ".txt")):
        return "spec-only"
    return "existing-code"


def status_rank(status):
    return SOURCE_STATUS_VALUES.index(status) if status in SOURCE_STATUS_VALUES else 99


def classify_entity(field, context):
    f = field.lower()
    c = context.lower()
    if not hasattr(classify_entity, "_canonical"):
        classify_entity._canonical = {
            sheet: {x.lower() for x in fields}
            for sheet, fields in CANONICAL.items()
        }
    canon = classify_entity._canonical
    candidates = []
    if any(x in c for x in ["player", "roster", "people", "person"]) or f in (canon["Player Fields"] | canon["Player Ratings"]):
        candidates.append("Player")
    if any(x in c for x in ["recruit", "prospect"]) or f in canon["Recruit Fields"]:
        candidates.append("Recruit")
    if any(x in c for x in ["coach"]) or f in canon["Coach Fields"]:
        candidates.append("Coach")
    if any(x in c for x in ["staff"]):
        candidates.append("Staff")
    if any(x in c for x in ["program"]) or f in canon["Program Fields"]:
        candidates.append("Program")
    if any(x in c for x in ["team", "teams"]) or f in canon["Team Fields"]:
        candidates.append("Team")
    if (
        any(x in c for x in ["school", "brand", "teamb"])
        or f in canon["School Brand Fields"]
    ):
        candidates.append("School Brand")
    if any(x in c for x in ["stadium", "venue"]) or f in canon["Stadium Fields"]:
        candidates.append("Stadium")
    if any(x in c for x in ["uniform"]) or f in canon["Uniform Fields"]:
        candidates.append("Uniform")
    if "nil" in c or "nil" in f:
        candidates.append("NIL")
    if any(x in c for x in ["game", "match"]) or f in canon["Game Fields"]:
        candidates.append("Game")
    if any(x in c for x in ["schedule", "calendar", "agenda"]) or f in canon["Schedule Fields"]:
        candidates.append("Schedule")
    if any(x in c for x in ["conference", "realignment"]) or f in canon["Conference Fields"]:
        candidates.append("Conference")
    if any(x in c for x in ["ranking", "rank", "award"]) or f in canon["Ranking Fields"]:
        candidates.append("Ranking")
    if any(x in c for x in ["notification", "event", "news"]) or f in canon["News Event Fields"]:
        candidates.append("News Event")
    if any(x in c for x in ["sim", "play", "drive", "engine", "tendenc", "gameplan"]) or f in canon["Simulation Fields"]:
        candidates.append("Simulation")
    if any(x in c for x in ["playbook", "scheme", "formation", "concept"]) or f in canon["Playbook - Scheme Fields"]:
        candidates.append("Playbook / Scheme")
    return candidates or ["Unclassified"]


def all_text_files():
    include_exts = {".js", ".ts", ".tsx", ".json", ".md", ".csv", ".yaml", ".yml", ".sql", ".txt", ".html"}
    skip_dirs = {".git", ".venv", "node_modules", "artifacts", "tmp", "runs", "archive", "data_model_inventory_csv"}
    files = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        parts = set(path.relative_to(ROOT).parts)
        if parts & skip_dirs:
            continue
        if "Screens for game" in path.parts or path.suffix.lower() == ".svg":
            continue
        if path.suffix.lower() in include_exts:
            files.append(path)
    return sorted(files)


def walk_json(value, path, source, line_hint, out):
    if isinstance(value, dict):
        for k, v in value.items():
            out.append((str(k), v, source, line_hint, ".".join(path + [str(k)])))
            walk_json(v, path + [str(k)], source, line_hint, out)
    elif isinstance(value, list):
        for i, item in enumerate(value[:25]):
            walk_json(item, path + [f"[{i}]"], source, line_hint, out)


def parse_js_object_keys(text, path):
    found = []
    array_name = None
    lines = text.splitlines()
    for idx, line in enumerate(lines, 1):
        stripped = line.strip()
        m_arr = re.match(r"(?:const|let|var)\s+([A-Z0-9_]+)\s*=\s*\[", stripped)
        if m_arr:
            array_name = m_arr.group(1)
        if array_name:
            for sm in re.finditer(r'"([A-Za-z][A-Za-z0-9_\- ]{1,60})"', line):
                found.append((sm.group(1), sm.group(1), path, idx, array_name))
            if "]" in stripped and not stripped.endswith(","):
                array_name = None
        for m in re.finditer(r"(?<=[{,])\s*([A-Za-z_$][A-Za-z0-9_$]*)\s*:", line):
            key = m.group(1)
            if key in {"if", "for", "while", "switch", "return"}:
                continue
            val = None
            vm = re.search(rf"{re.escape(key)}\s*:\s*([^,}}]+)", line)
            if vm:
                raw = vm.group(1).strip().strip("'\"")
                val = raw[:80]
            context = " ".join(lines[max(0, idx - 5): min(len(lines), idx + 4)])
            found.append((key, val, path, idx, context))
    return found


def parse_csv_headers(path):
    out = []
    try:
        with open(path, newline="", encoding="utf-8-sig") as f:
            reader = csv.reader(f)
            headers = next(reader, [])
            row = next(reader, [])
        for i, h in enumerate(headers):
            if h:
                out.append((h, row[i] if i < len(row) else "", path, 1, f"CSV header {i + 1}"))
    except Exception as exc:
        out.append(("__parse_error__", str(exc), path, 1, "CSV parse error"))
    return out


def parse_json_file(path):
    out = []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        walk_json(data, [], path, "JSON traversal", out)
    except Exception as exc:
        out.append(("__parse_error__", str(exc), path, 1, "JSON parse error"))
    return out


def docs_mentions(files):
    mentioned = defaultdict(list)
    wanted = set()
    for fields in CANONICAL.values():
        wanted.update(fields)
    for trait, *_ in RECOMMENDED_TRAITS:
        wanted.add(trait)
    lower_fields = {w.lower(): w for w in wanted}
    simple_fields = {k: v for k, v in lower_fields.items() if len(k) >= 3}
    for path in files:
        if path.suffix.lower() not in {".md", ".txt", ".sql"}:
            continue
        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except Exception:
            continue
        for i, line in enumerate(lines, 1):
            low = line.lower()
            for lf, original in simple_fields.items():
                if lf in low:
                    mentioned[original.lower()].append((path, i, line.strip()[:180]))
    return mentioned


def collect_discoveries(files):
    discoveries = []
    errors = []
    for path in files:
        ext = path.suffix.lower()
        try:
            if ext == ".csv":
                discoveries.extend(parse_csv_headers(path))
            elif ext == ".json":
                discoveries.extend(parse_json_file(path))
            elif ext in {".js", ".ts", ".tsx", ".html"}:
                text = path.read_text(encoding="utf-8", errors="replace")
                discoveries.extend(parse_js_object_keys(text, path))
            elif ext in {".md", ".txt", ".sql", ".yaml", ".yml"}:
                # Docs are incorporated by direct mentions against canonical/recommended fields.
                continue
        except Exception as exc:
            errors.append((path, exc))
    return discoveries, errors


def build_field_index(discoveries):
    index = defaultdict(list)
    enums = defaultdict(list)
    for field, example, path, loc, context in discoveries:
        if field == "__parse_error__":
            continue
        status = source_status(path)
        entities = classify_entity(field, f"{rel(path)} {context}")
        for entity in entities:
            index[(entity, str(field).lower())].append({
                "field": str(field),
                "example": example,
                "source": rel(path),
                "loc": str(loc),
                "status": status,
                "context": str(context)[:240],
            })
        if isinstance(context, str) and re.match(r"^[A-Z0-9_]{3,}$", context):
            enums[context].append({
                "value": field,
                "source": rel(path),
                "loc": str(loc),
                "status": status,
            })
    return index, enums


def best_hit(hits):
    if not hits:
        return None
    return sorted(hits, key=lambda h: (status_rank(h["status"]), len(h["source"])))[0]


def make_entity_row(entity, field, hit=None, status=None, notes="", recommendation="Review/decide"):
    status = status or (hit["status"] if hit else "missing-but-needed")
    source = hit["source"] if hit else ""
    loc = hit["loc"] if hit else ""
    example = hit["example"] if hit and hit["example"] is not None else ""
    dtype = infer_type(example) if hit else ""
    current_usage = ""
    if hit:
        if hit["status"] == "existing-code":
            current_usage = "Referenced in active JS/runtime/harness code."
        elif hit["status"] == "mock-only":
            current_usage = "Present in data/mock/generated run output."
        elif hit["status"] == "spec-only":
            current_usage = "Present in docs/spec/stub pack."
    return [
        entity,
        field,
        display_label(field),
        dtype,
        str(example)[:180],
        status,
        source,
        loc,
        "",
        "",
        "",
        "",
        current_usage,
        "",
        "",
        "Yes" if status in {"existing-code", "mock-only"} and entity in {"Simulation", "Ranking"} else "",
        "Yes" if status in {"existing-code", "mock-only"} else "TBD",
        notes,
        recommendation,
        "pending-review",
    ]


def build_sheets(files, discoveries, errors):
    doc_hits = docs_mentions(files)
    field_index, enums = build_field_index(discoveries)
    sheets = {name: [] for name in SHEETS}
    entity_field_counts = defaultdict(int)
    entity_primary = {}
    entity_statuses = defaultdict(list)

    for sheet, entity in TAB_TO_ENTITY.items():
        fields = CANONICAL.get(sheet, [])
        seen = set()
        for field in fields:
            key = (entity, field.lower())
            hit = best_hit(field_index.get(key, []))
            status = None
            notes = ""
            recommendation = "Review/approve field"
            if not hit and field.lower() in doc_hits:
                source_path, source_line, context = doc_hits[field.lower()][0]
                hit = {"field": field, "example": "", "source": rel(source_path), "loc": str(source_line), "status": "spec-only", "context": context}
            if not hit:
                if sheet in {"Player Ratings", "Player Traits", "Recommended Additions"}:
                    status = "missing-but-needed"
                    recommendation = "Recommended future review item"
                elif field in {"name", "id", "position", "record", "status", "week"}:
                    status = "missing-but-needed"
                else:
                    status = "inferred" if any(x in field.lower() for x in ["status", "role", "budget", "grade", "fit", "expectation"]) else "missing-but-needed"
                notes = "Not found as a current field in scanned code/data; included from requested inventory scope or implied game concept."
            row = make_entity_row(entity, field, hit=hit, status=status, notes=notes, recommendation=recommendation)
            sheets[sheet].append(row)
            seen.add(field.lower())

        # Add extra discovered fields for the entity that were not in the canonical list.
        for (hit_entity, field_lower), hits in sorted(field_index.items()):
            if hit_entity != entity or field_lower in seen:
                continue
            hit = best_hit(hits)
            if hit and hit["field"] not in {"__parse_error__"}:
                sheets[sheet].append(make_entity_row(entity, hit["field"], hit=hit, notes="Discovered by repo scanner; not part of the seed checklist.", recommendation="Review/keep if still needed"))
                seen.add(field_lower)

        entity_field_counts[entity] = len(sheets[sheet])
        for row in sheets[sheet]:
            entity_statuses[entity].append(row[5])
            if row[6] and entity not in entity_primary:
                entity_primary[entity] = row[6]

    # Player traits have a specialized tab.
    trait_rows = []
    for trait, category, desc, polarity, sim, rec, dev, morale, impact in RECOMMENDED_TRAITS:
        hit = best_hit(field_index.get(("Player", trait.lower()), []))
        if not hit and trait.lower() in doc_hits:
            p, line, context = doc_hits[trait.lower()][0]
            hit = {"source": rel(p), "loc": str(line), "status": "spec-only"}
        status = hit["status"] if hit else "missing-but-needed"
        trait_rows.append([trait, category, desc, polarity, sim, rec, dev, morale, impact, status, hit["source"] if hit else "", hit["loc"] if hit else "", "pending-review"])
    sheets["Player Traits"] = trait_rows
    entity_field_counts["Player Trait"] = len(trait_rows)
    entity_statuses["Player Trait"].extend([r[9] for r in trait_rows])
    if trait_rows:
        entity_primary["Player Trait"] = trait_rows[0][10]

    # UI mapping.
    for screen, fields in SCREEN_FIELD_HINTS.items():
        for entity, field in fields:
            sheets["UI Display Mapping"].append([
                screen,
                "Primary data surface",
                entity,
                field,
                display_label(field),
                "Yes" if screen in {"Roster", "Player Profile", "Dashboard", "Schedule"} else "TBD",
                "TBD",
                "No" if screen not in {"School Creator", "Uniform Creator", "NIL Management"} else "TBD",
                "Yes" if screen in {"Roster", "Recruiting Board", "Rankings", "Schedule"} else "",
                "Yes" if screen in {"Roster", "Recruiting Board", "Schedule"} else "",
                "Yes",
                "No" if screen in {"Roster", "Dashboard", "Schedule"} else "TBD",
                "Seed mapping for human review; screen implementation may not exist yet.",
                "pending-review",
            ])

    # Enums/value lists from constant arrays plus common explicit lists.
    for list_name, values in sorted(enums.items()):
        for item in values:
            sheets["Enums & Value Lists"].append([list_name, item["value"], item["status"], item["source"], item["loc"], "", "Discovered constant/list value.", "pending-review"])
    for list_name, values in {
        "ApprovalStatus": ["pending-review", "approved", "rejected", "revise"],
        "SourceStatus": SOURCE_STATUS_VALUES,
        "PlayerPositions": ["QB", "HB", "RB", "WR", "TE", "OT", "OG", "C", "EDGE", "DL", "LB", "CB", "S", "K", "P", "LS"],
        "PlayerClasses": ["FR", "SO", "JR", "SR", "RS-FR", "RS-SO", "RS-JR", "RS-SR"],
        "MoraleStates": ["High", "Stable", "Low"],
        "GameStatuses": ["upcoming", "final", "in-progress"],
    }.items():
        existing = {(r[0], r[1]) for r in sheets["Enums & Value Lists"]}
        for v in values:
            if (list_name, v) not in existing:
                sheets["Enums & Value Lists"].append([list_name, v, "inferred", "", "", "", "Useful review list; not necessarily enforced in code.", "pending-review"])

    # Missing/ambiguous.
    for path, exc in errors:
        sheets["Missing - Ambiguous Fields"].append(["Could not parse file", "", "", rel(path), str(exc), "Inspect manually or improve scanner/parser.", "High", "pending-review"])
    duplicate_names = defaultdict(set)
    for (entity, field), hits in field_index.items():
        statuses = {h["status"] for h in hits}
        sources = {h["source"] for h in hits}
        if len(statuses) > 1 and len(sources) > 1:
            duplicate_names[(entity, field)].update(sources)
    for (entity, field), sources in sorted(duplicate_names.items()):
        sheets["Missing - Ambiguous Fields"].append([
            "Field appears across multiple source statuses",
            entity,
            field,
            "; ".join(sorted(sources)[:6]),
            "May be code, mock, and spec using the same name with different meaning.",
            "Review before merging or renaming.",
            "Medium",
            "pending-review",
        ])
    for sheet, entity in TAB_TO_ENTITY.items():
        for row in sheets[sheet]:
            if row[5] in {"missing-but-needed", "inferred"}:
                sheets["Missing - Ambiguous Fields"].append([
                    f"{row[5]} field",
                    entity,
                    row[1],
                    row[6],
                    "Needed for concept review but not confirmed as a current game field.",
                    "Approve/reject/rename during data model review.",
                    "Medium" if row[5] == "missing-but-needed" else "Low",
                    "pending-review",
                ])

    # Recommended additions, prioritizing concept gaps.
    for sheet, entity in TAB_TO_ENTITY.items():
        for row in sheets[sheet]:
            if row[5] in {"missing-but-needed", "inferred"}:
                sheets["Recommended Additions"].append([
                    entity,
                    row[1],
                    row[3] or "TBD",
                    "Included in requested review scope but not found as an active field.",
                    row[14] or row[13] or "TBD",
                    "TBD",
                    "High" if entity in {"Player", "Simulation", "Recruit", "Team"} else "Medium",
                    "pending-review",
                ])

    # Entity index.
    descriptions = {
        "Player": "Roster/player identity, status, development, and display fields.",
        "Player Rating": "Physical, technical, mental, football IQ, and position-specific ratings.",
        "Player Development": "Long-term player growth and practice/development controls.",
        "Player Trait": "Qualitative player traits that may affect sim, recruiting, morale, or growth.",
        "Recruit": "Prospect/recruiting board and prospect detail fields.",
        "Coach": "Head coach/coordinator/position coach attributes and contract/reputation fields.",
        "Staff": "Support staff and staff-card fields.",
        "Team": "Team-season state, ratings, identity link fields, and roster aggregates.",
        "Program": "Long-term school/program state and institutional metrics.",
        "School Brand": "TeamBrand/school identity, color, logo, gradient, and branding fields.",
        "Stadium": "Venue identity, capacity, quality, atmosphere, and upgrade fields.",
        "Uniform": "Uniform creator/equipment appearance fields.",
        "NIL": "NIL budget, collective, offer, and player/recruit NIL fields.",
        "Game": "Scheduled/played game, score, venue, and result fields.",
        "Schedule": "Calendar, agenda, notification, and schedule-row fields.",
        "Conference": "Conference identity, membership, tier, and realignment fields.",
        "Ranking": "Poll/ranking/award/standings related fields.",
        "News Event": "Inbox, notification, event, and timeline fields.",
        "Simulation": "Game engine, play event, probability, game plan, and result fields.",
        "Playbook / Scheme": "Scheme, formation, concept, personnel, and game-plan fields.",
    }
    for entity in sorted(entity_field_counts):
        statuses = entity_statuses[entity]
        if "existing-code" in statuses:
            st = "existing-code"
        elif "mock-only" in statuses:
            st = "mock-only"
        elif "spec-only" in statuses:
            st = "spec-only"
        else:
            st = "inferred"
        related_screens = ", ".join(sorted({screen for screen, fields in SCREEN_FIELD_HINTS.items() for e, _ in fields if e == entity})[:8])
        sheets["Entity Index"].append([
            entity,
            descriptions.get(entity, "Inventory entity discovered or implied by code/specs."),
            st,
            entity_primary.get(entity, ""),
            entity_field_counts[entity],
            related_screens,
            "",
            "Review field rows for source status before approving.",
            "pending-review",
        ])

    # README and change log.
    scan_roots = sorted({rel(f).split("/")[0] for f in files})
    skipped = [".git", ".venv", "node_modules", "artifacts", "tmp", "data_model_inventory_csv generated exports", "harness/runs generated outputs", "docs/archive", "Screens for game", "*.svg/images"]
    sheets["README"] = [
        ["Date generated", datetime.now().isoformat(timespec="seconds")],
        ["Repo path inspected", str(ROOT)],
        ["Files scanned", f"{len(files)} text/source files"],
        ["Folders scanned", ", ".join(scan_roots)],
        ["Folders/files excluded", ", ".join(skipped)],
        ["Source Status: existing-code", "Field/key found in active app, runtime, harness, scripts, or root source files."],
        ["Source Status: mock-only", "Field/key found only in data packs, generated sample data, CSV/JSON run output, or mocks."],
        ["Source Status: spec-only", "Field/key found in docs, planning packs, stubs, or specs but not active app code."],
        ["Source Status: inferred", "Field was included because the game concept or requested inventory implies it, but it was not verified in current code/data."],
        ["Source Status: missing-but-needed", "Field is recommended/needed for the target concept but was not found as current code/data."],
        ["Source Status: duplicate/unclear", "Field appears in inconsistent or ambiguous contexts."],
        ["Approval Status", "All rows default to pending-review. Change to approved, rejected, or revise during human review."],
        ["Worksheet name note", "Excel does not allow / in tab names, so the requested Playbook / Scheme Fields and Missing / Ambiguous Fields tabs are named Playbook - Scheme Fields and Missing - Ambiguous Fields."],
        ["Warning", "Do not treat inferred/spec-only/missing rows as implemented game fields."],
        ["Next step", "Review tabs by entity, update Approval Status and Recommendation, then decide which fields map to each screen."],
    ]
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        commit = ""
    sheets["Change Log"] = [[datetime.now().date().isoformat(), "Generated data model inventory workbook and CSV exports.", "Documentation/inventory only; no game functionality changed.", "Codex", commit]]
    return sheets


def write_csvs(sheets):
    OUT_CSV_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_CSV_DIR.glob("*.csv"):
        old.unlink()
    headers_by_sheet = headers_map()
    for sheet, rows in sheets.items():
        safe = re.sub(r"[^A-Za-z0-9]+", "_", sheet).strip("_").lower()
        with open(OUT_CSV_DIR / f"{safe}.csv", "w", newline="", encoding="utf-8-sig") as f:
            writer = csv.writer(f)
            writer.writerow(headers_by_sheet[sheet])
            if rows:
                writer.writerows(rows)
            else:
                writer.writerow(["No current fields found"])


def headers_map():
    result = {}
    for sheet in SHEETS:
        if sheet == "README":
            result[sheet] = ["Topic", "Details"]
        elif sheet == "Entity Index":
            result[sheet] = ENTITY_INDEX_HEADERS
        elif sheet == "Player Traits":
            result[sheet] = TRAIT_HEADERS
        elif sheet == "UI Display Mapping":
            result[sheet] = UI_HEADERS
        elif sheet == "Enums & Value Lists":
            result[sheet] = ENUM_HEADERS
        elif sheet == "Missing - Ambiguous Fields":
            result[sheet] = MISSING_HEADERS
        elif sheet == "Recommended Additions":
            result[sheet] = RECOMMENDED_HEADERS
        elif sheet == "Change Log":
            result[sheet] = CHANGE_HEADERS
        else:
            result[sheet] = ENTITY_HEADERS
    return result


def style_sheet(ws):
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1F2937")
        cell.alignment = Alignment(wrap_text=True, vertical="top")
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    for idx, col in enumerate(ws.columns, 1):
        max_len = 0
        for cell in col:
            val = "" if cell.value is None else str(cell.value)
            max_len = max(max_len, min(len(val), 80))
        ws.column_dimensions[get_column_letter(idx)].width = max(12, min(42, max_len + 2))
    headers = [c.value for c in ws[1]]
    for target_header in ["Source Status", "Approval Status"]:
        if target_header in headers:
            col = headers.index(target_header) + 1
            letter = get_column_letter(col)
            for status, color in STATUS_COLORS.items():
                ws.conditional_formatting.add(
                    f"{letter}2:{letter}{max(ws.max_row, 2)}",
                    FormulaRule(formula=[f'{letter}2="{status}"'], fill=PatternFill("solid", fgColor=color)),
                )


def write_workbook(sheets):
    wb = Workbook()
    default = wb.active
    wb.remove(default)
    headers_by_sheet = headers_map()
    for sheet in SHEETS:
        ws = wb.create_sheet(sheet)
        ws.append(headers_by_sheet[sheet])
        rows = sheets.get(sheet, [])
        if rows:
            for row in rows:
                ws.append(row)
        else:
            ws.append(["No current fields found"])
        style_sheet(ws)
    wb.save(OUT_XLSX)


def verify_workbook():
    wb = load_workbook(OUT_XLSX, read_only=False)
    missing = [s for s in SHEETS if s not in wb.sheetnames]
    no_headers = []
    for s in SHEETS:
        if s in wb.sheetnames:
            ws = wb[s]
            if ws.max_row < 1 or ws.max_column < 1 or ws.cell(1, 1).value in (None, ""):
                no_headers.append(s)
    return {
        "exists": OUT_XLSX.exists(),
        "sheet_count": len(wb.sheetnames),
        "missing_sheets": missing,
        "no_headers": no_headers,
        "sheets": wb.sheetnames,
    }


def main():
    files = all_text_files()
    discoveries, errors = collect_discoveries(files)
    sheets = build_sheets(files, discoveries, errors)
    write_csvs(sheets)
    write_workbook(sheets)
    verification = verify_workbook()
    entity_count = len(sheets["Entity Index"])
    field_count = sum(len(sheets[s]) for s in TAB_TO_ENTITY) + len(sheets["Player Traits"])
    inferred_count = sum(1 for s in TAB_TO_ENTITY for r in sheets[s] if len(r) > 5 and r[5] == "inferred")
    inferred_count += sum(1 for r in sheets["Player Traits"] if len(r) > 9 and r[9] == "inferred")
    missing_count = sum(1 for s in TAB_TO_ENTITY for r in sheets[s] if len(r) > 5 and r[5] == "missing-but-needed")
    missing_count += sum(1 for r in sheets["Player Traits"] if len(r) > 9 and r[9] == "missing-but-needed")
    summary = {
        "status": "PASS" if verification["exists"] and not verification["missing_sheets"] and not verification["no_headers"] else "FAIL",
        "workbook_path": str(OUT_XLSX),
        "csv_folder_path": str(OUT_CSV_DIR),
        "entities_found": entity_count,
        "fields_inventoried": field_count,
        "inferred_fields": inferred_count,
        "missing_or_recommended_fields": missing_count,
        "files_scanned": len(files),
        "source_folders_scanned": sorted({rel(f).split("/")[0] for f in files}),
        "source_folders_skipped": [".git", ".venv", "node_modules", "artifacts", "tmp", "data_model_inventory_csv generated exports", "harness/runs generated outputs", "docs/archive", "Screens for game", "*.svg/images"],
        "parse_errors": len(errors),
        "verification": verification,
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
