import csv
import re
import subprocess
from datetime import datetime
from pathlib import Path

from openpyxl import Workbook, load_workbook
from openpyxl.formatting.rule import FormulaRule
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


ROOT = Path(__file__).resolve().parents[1]
OUT_XLSX = ROOT / "cfl_proposed_data_model_inventory.xlsx"
OUT_CSV_DIR = ROOT / "proposed_data_model_inventory_csv"

SHEETS = [
    "README",
    "Architecture Principles",
    "Entity Index",
    "Core World Tables",
    "Person - Player Model",
    "Recruiting Model",
    "Coach - Staff Model",
    "School - Program Model",
    "Years - Calendar Model",
    "Conference - Competition Model",
    "Game - Schedule Model",
    "Schemes - Playbooks Model",
    "Rulesets Model",
    "Relationship Tables",
    "History - Snapshot Tables",
    "Transactions Model",
    "Scouting - Knowledge Model",
    "NIL - Finance Model",
    "Facilities - Brand Model",
    "Events - Inbox - News Model",
    "Simulation Engine Model",
    "Resources - UI Contracts",
    "Enums - Value Lists",
    "Implementation Milestones",
    "Quality Gates",
    "Open Questions",
    "Change Log",
]

FIELD_HEADERS = [
    "Logical Entity",
    "Table / Store",
    "Field Name",
    "Display Label",
    "Data Type",
    "Example Value",
    "Parent Entity",
    "Entity Layer",
    "FM-Inspired Pattern",
    "Source Basis",
    "Build Phase",
    "Screen Usage",
    "Simulation Usage",
    "Editable By User?",
    "Persistence Needed?",
    "Notes",
    "Approval Status",
]

ENTITY_INDEX_HEADERS = [
    "Entity Name",
    "Entity Type",
    "Description",
    "Parent Entity",
    "Primary Table / Store",
    "Key Relationships",
    "FM-Inspired Pattern",
    "Build Phase",
    "Notes",
    "Approval Status",
]

PRINCIPLE_HEADERS = ["Principle", "Why It Exists", "FM/Planning Signal", "Implementation Implication", "Approval Status"]
MILESTONE_HEADERS = ["Phase", "Goal", "Tables Required", "Selectors / Actions Required", "Quality Gate", "Approval Status"]
QUALITY_HEADERS = ["Gate", "Applies To", "Required Check", "Failure Means", "Automation Candidate", "Approval Status"]
OPEN_HEADERS = ["Question", "Affected Entity / Table", "Why It Matters", "Default Recommendation", "Decision Needed By", "Approval Status"]
CHANGE_HEADERS = ["date", "action", "notes", "generated by", "repo commit hash if available"]

SOURCE_COLORS = {
    "FM-derived architecture": "D9EAD3",
    "planning-doc": "D9E1F2",
    "domain-design": "FFF2CC",
    "current-overlap": "DDEBF7",
    "recommended": "FCE4D6",
}

APPROVAL_COLORS = {
    "pending-review": "FFF2CC",
    "approved": "C6EFCE",
    "rejected": "F4CCCC",
    "revise": "FCE4D6",
}


def label(field):
    return re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", field).replace("_", " ").replace("-", " ").title()


def row(entity, table, field, dtype, example="", parent="", layer="world", fm="", basis="domain-design",
        phase="M0+", screen="", sim="", editable="No", persist="Yes", notes=""):
    return [
        entity,
        table,
        field,
        label(field),
        dtype,
        example,
        parent,
        layer,
        fm,
        basis,
        phase,
        screen,
        sim,
        editable,
        persist,
        notes,
        "pending-review",
    ]


def rows_for(entity, table, fields, parent="", layer="world", fm="", basis="domain-design", phase="M0+",
             screen="", sim="", editable="No", persist="Yes"):
    result = []
    for item in fields:
        if len(item) == 2:
            field, dtype = item
            example = ""
            notes = ""
        elif len(item) == 3:
            field, dtype, example = item
            notes = ""
        else:
            field, dtype, example, notes = item
        result.append(row(entity, table, field, dtype, example, parent, layer, fm, basis, phase, screen, sim, editable, persist, notes))
    return result


def build_model():
    sheets = {s: [] for s in SHEETS}

    sheets["Architecture Principles"] = [
        ["Person first, roles second", "Players, recruits, coaches, staff, and created people share a base human identity.", "FM separates people/basic people and player/non-player history.", "Use Person as the root, then attach athlete, recruit, coach, and staff profiles.", "pending-review"],
        ["Relationships are records", "Scholarships, roster membership, staff contracts, depth chart slots, conference membership, NIL deals, and visits all have lifecycle.", "FM-style object links and transaction/history stores.", "Use join tables with IDs, status, dates, and history instead of nested copies.", "pending-review"],
        ["Current state is not history", "Profiles need long-term memory without turning live records into giant blobs.", "FM player/non-player history and indexed save stores.", "Keep current tables lean; append histories and snapshots separately.", "pending-review"],
        ["Calendar drives the world", "Continue is a system pipeline, not a button that increments a number.", "FM fixture rules, date windows, transfer windows, event deadlines.", "Model seasons, weeks, phases, windows, blockers, scheduled jobs, and events.", "pending-review"],
        ["Rulesets are versioned", "College rules change and saves must remain stable.", "FM database versions and editor overlays.", "Store active ruleset version and migration metadata in each save.", "pending-review"],
        ["Scouting is uncertainty", "A player should not know true ratings until enough knowledge exists.", "FM scouted person and attribute snapshot signals.", "Store true ratings separately from scouted snapshots, confidence, and staff bias.", "pending-review"],
        ["Actions emit logs", "Every meaningful click should leave a durable trace.", "FM actions/resources plus current action/event log direction.", "Commands write action log, event log, changed records, and invariants.", "pending-review"],
        ["UI is resource-driven", "Dense menus need consistent actions, columns, tabs, routes, and inspectors.", "FM action/menu/panel/resource catalog pattern.", "Store workspace/action/column/menu definitions as resources.", "pending-review"],
    ]

    # Core world/save.
    sheets["Core World Tables"] += rows_for("World Save", "world_saves", [
        ("worldId", "id", "world_0001"),
        ("saveSchemaVersion", "integer", "1"),
        ("baseWorldVersion", "string", "cfl_base_2026_01"),
        ("rulesetId", "foreign-key", "ruleset_modern_2026"),
        ("worldSeed", "string", "lakeview-2031-001"),
        ("userProgramId", "foreign-key", "program_vanderbilt"),
        ("currentSeasonId", "foreign-key", "season_2031"),
        ("currentWeekId", "foreign-key", "week_2031_04"),
        ("currentPhaseId", "foreign-key", "regular_season"),
        ("createdAt", "datetime", "2031-01-01T00:00:00Z"),
        ("updatedAt", "datetime", "2031-09-18T12:00:00Z"),
    ], fm="WORLD store with versioned save metadata", basis="FM-derived architecture", phase="M0")
    sheets["Core World Tables"] += rows_for("Object Reference", "object_refs", [
        ("objectRefId", "id", "ref_player_123"),
        ("objectType", "enum", "player"),
        ("objectId", "id", "person_123"),
        ("parentType", "enum", "program"),
        ("parentId", "id", "program_vanderbilt"),
        ("sourceWorkspaceId", "foreign-key", "roster"),
        ("intent", "enum", "open_profile"),
    ], layer="resource", fm="Object link/action target pattern", basis="FM-derived architecture", phase="M0")
    sheets["Core World Tables"] += rows_for("Migration", "schema_migrations", [
        ("migrationId", "id", "migration_0001"),
        ("fromVersion", "integer", "1"),
        ("toVersion", "integer", "2"),
        ("subsystem", "string", "recruiting"),
        ("appliedAt", "datetime", ""),
        ("notes", "text", ""),
    ], layer="persistence", fm="Database version and patch overlay pattern", basis="FM-derived architecture", phase="M0")

    # Person/player/recruit model.
    sheets["Person - Player Model"] += rows_for("Person", "people", [
        ("personId", "id", "person_2031_000123"),
        ("firstName", "string", "Darius"),
        ("lastName", "string", "McClain"),
        ("displayName", "string", "Darius McClain"),
        ("dateOfBirth", "date", "2012-04-18"),
        ("age", "computed-integer", "18"),
        ("hometownCity", "string", "Tulsa"),
        ("hometownState", "enum", "OK"),
        ("regionId", "foreign-key", "region_southern_plains"),
        ("nationality", "string", "USA"),
        ("createdBy", "enum", "generated"),
        ("isRetired", "boolean", "false"),
        ("archived", "boolean", "false"),
    ], fm="Basic people/live people separation", basis="FM-derived architecture", phase="M0")
    sheets["Person - Player Model"] += rows_for("Athlete Profile", "athlete_profiles", [
        ("personId", "foreign-key", "person_2031_000123"),
        ("primaryPositionId", "foreign-key", "pos_qb"),
        ("secondaryPositionIds", "array<foreign-key>", "pos_ath"),
        ("heightInches", "integer", "74"),
        ("weightPounds", "integer", "196"),
        ("handedness", "enum", "right"),
        ("bodyProfileId", "foreign-key", "body_long_frame"),
        ("frameGrowthRemaining", "integer 0-100", "42"),
        ("currentAbility", "integer 1-100", "69"),
        ("potentialAbility", "integer 1-100", "88"),
        ("developmentCurveId", "foreign-key", "late_developer"),
        ("personalityProfileId", "foreign-key", "personality_competitor"),
    ], parent="Person", fm="Player-specific live profile attached to person", basis="planning-doc", phase="M1")
    sheets["Person - Player Model"] += rows_for("Player Rating Snapshot", "player_rating_snapshots", [
        ("snapshotId", "id", "rating_snap_0001"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("source", "enum", "true_current"),
        ("ratingSetId", "foreign-key", "rating_set_qb_v1"),
        ("overall", "integer 1-100", "78"),
        ("positionOverall", "json", "{QB:78, ATH:74}"),
        ("attributesJson", "json", "{throwPower:82, processing:61}"),
        ("certainty", "integer 0-100", "100"),
        ("createdAt", "datetime", ""),
    ], parent="Athlete Profile", layer="history/snapshot", fm="PLAYER_ATTRIBUTE_SNAPSHOT", basis="FM-derived architecture", phase="M2")
    sheets["Person - Player Model"] += rows_for("Player Trait Assignment", "player_trait_assignments", [
        ("assignmentId", "id", "trait_asg_0001"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("traitId", "foreign-key", "trait_film_junkie"),
        ("intensity", "integer 1-5", "4"),
        ("visibility", "enum", "scouted"),
        ("sourceSnapshotId", "foreign-key", "scout_snap_003"),
        ("startWeekId", "foreign-key", "week_2031_01"),
        ("endWeekId", "nullable foreign-key", ""),
    ], parent="Person", layer="relationship", fm="Trait/knowledge as attached records, not separate entity sibling", basis="domain-design", phase="M2")
    sheets["Person - Player Model"] += rows_for("Roster Membership", "player_program_memberships", [
        ("membershipId", "id", "ppm_0001"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("seasonId", "foreign-key", "season_2031"),
        ("classYear", "enum", "FR"),
        ("eligibilityYearsRemaining", "integer", "4"),
        ("redshirtStatus", "enum", "available"),
        ("scholarshipStatus", "enum", "scholarship"),
        ("jerseyNumber", "integer", "12"),
        ("rosterStatus", "enum", "active"),
        ("joinedVia", "enum", "recruiting"),
        ("startDate", "date", "2031-01-10"),
        ("endDate", "nullable date", ""),
    ], parent="Person", layer="relationship", fm="Playing history/current club separated by membership", basis="FM-derived architecture", phase="M1")
    sheets["Person - Player Model"] += rows_for("Player State", "player_weekly_state", [
        ("stateId", "id", "pstate_0001"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("morale", "integer 0-100", "72"),
        ("confidence", "integer 0-100", "68"),
        ("fatigue", "integer 0-100", "31"),
        ("healthStatus", "enum", "available"),
        ("academicStatus", "enum", "good_standing"),
        ("practiceLoad", "enum", "normal"),
        ("playingTimeExpectation", "enum", "rotation"),
    ], parent="Roster Membership", layer="snapshot", fm="Current status snapshots feed player/profile tables", basis="planning-doc", phase="M2")

    # Recruiting.
    sheets["Recruiting Model"] += rows_for("Recruiting Profile", "recruiting_profiles", [
        ("recruitingProfileId", "id", "recprof_0001"),
        ("personId", "foreign-key", "person_2032_000234"),
        ("recruitingClassId", "foreign-key", "class_2032"),
        ("gradeLevel", "enum", "SR"),
        ("highSchoolId", "foreign-key", "hs_tulsa_union"),
        ("publicStars", "integer 1-5", "4"),
        ("publicNationalRank", "integer", "188"),
        ("publicStateRank", "integer", "4"),
        ("publicPositionRank", "integer", "13"),
        ("recruitStatus", "enum", "open"),
        ("commitmentProgramId", "nullable foreign-key", ""),
        ("signedProgramId", "nullable foreign-key", ""),
    ], parent="Person", layer="facet", fm="SCOUTED_PERSON and recruiting profile attached to person", basis="planning-doc", phase="M3")
    sheets["Recruiting Model"] += rows_for("Recruit Program Interest", "recruit_program_interest", [
        ("interestId", "id", "rpi_0001"),
        ("personId", "foreign-key", "person_2032_000234"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("seasonId", "foreign-key", "season_2031"),
        ("interestScore", "integer 0-100", "61"),
        ("relationshipScore", "integer 0-100", "44"),
        ("schemeFitScore", "integer 0-100", "78"),
        ("playingTimeFitScore", "integer 0-100", "82"),
        ("academicFitScore", "integer 0-100", "55"),
        ("nilFitScore", "integer 0-100", "49"),
        ("distanceFitScore", "integer 0-100", "35"),
        ("priority", "enum", "high"),
        ("staffOwnerId", "foreign-key", "coach_004"),
        ("lastContactWeekId", "foreign-key", "week_2031_04"),
        ("flipRisk", "integer 0-100", "22"),
    ], parent="Recruiting Profile", layer="relationship", fm="Relationship records with lifecycle/status", basis="FM-derived architecture", phase="M3")
    sheets["Recruiting Model"] += rows_for("Recruiting Action", "recruiting_actions", [
        ("recruitingActionId", "id", "ra_0001"),
        ("actionType", "enum", "contact"),
        ("personId", "foreign-key", "person_2032_000234"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("actorCoachId", "foreign-key", "coach_004"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("resourceCost", "integer", "2"),
        ("outcomeEventId", "foreign-key", "event_0008"),
        ("notes", "text", ""),
    ], parent="Recruit Program Interest", layer="action/log", fm="Action records dispatch event outcomes", basis="FM-derived architecture", phase="M3")
    sheets["Recruiting Model"] += rows_for("Official Visit", "official_visits", [
        ("visitId", "id", "visit_0001"),
        ("personId", "foreign-key", "person_2032_000234"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("weekId", "foreign-key", "week_2031_09"),
        ("gameId", "nullable foreign-key", "game_2031_05"),
        ("status", "enum", "scheduled"),
        ("visitType", "enum", "official"),
        ("hostPersonId", "nullable foreign-key", "person_2031_000123"),
        ("pitchFocusId", "foreign-key", "pitch_playing_time"),
        ("resultScore", "nullable integer", ""),
        ("linkedCalendarEventId", "foreign-key", "cal_0009"),
    ], parent="Recruiting Profile", layer="relationship", fm="Scheduled events linked to player and offer", basis="FM-derived architecture", phase="M4")
    sheets["Recruiting Model"] += rows_for("Recruiting Promise", "recruiting_promises", [
        ("promiseId", "id", "promise_0001"),
        ("personId", "foreign-key", "person_2032_000234"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("promiseType", "enum", "early_playing_time"),
        ("madeWeekId", "foreign-key", "week_2031_08"),
        ("dueWeekId", "foreign-key", "week_2032_04"),
        ("status", "enum", "active"),
        ("confidenceImpact", "integer", "8"),
        ("breachSeverity", "enum", "major"),
    ], parent="Recruiting Profile", layer="relationship/history", fm="INTERACTION_PROMISE/PROMISE", basis="FM-derived architecture", phase="M4")

    # Coaches/staff.
    sheets["Coach - Staff Model"] += rows_for("Coach Profile", "coach_profiles", [
        ("personId", "foreign-key", "person_coach_001"),
        ("primaryRoleId", "foreign-key", "role_head_coach"),
        ("age", "integer", "48"),
        ("reputation", "integer 0-100", "74"),
        ("offensivePhilosophyId", "foreign-key", "scheme_spread_option"),
        ("defensivePhilosophyId", "foreign-key", "scheme_425"),
        ("personalityId", "foreign-key", "coach_detail_oriented"),
        ("ambition", "integer 1-20", "15"),
        ("loyalty", "integer 1-20", "11"),
        ("pressureHandling", "integer 1-20", "14"),
    ], parent="Person", layer="facet", fm="NON_PLAYER live profile attached to person", basis="FM-derived architecture", phase="M2")
    sheets["Coach - Staff Model"] += rows_for("Coach Attribute Snapshot", "coach_attribute_snapshots", [
        ("snapshotId", "id", "coach_attr_0001"),
        ("personId", "foreign-key", "person_coach_001"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("recruiting", "integer 1-20", "16"),
        ("playerDevelopment", "integer 1-20", "13"),
        ("playCalling", "integer 1-20", "15"),
        ("scouting", "integer 1-20", "12"),
        ("motivation", "integer 1-20", "14"),
        ("discipline", "integer 1-20", "10"),
        ("nilInfluence", "integer 1-20", "9"),
        ("certainty", "integer 0-100", "100"),
    ], parent="Coach Profile", layer="history/snapshot", fm="NON_PLAYER_ATTRIBUTE_SNAPSHOT", basis="FM-derived architecture", phase="M2")
    sheets["Coach - Staff Model"] += rows_for("Coach Contract", "coach_program_contracts", [
        ("contractId", "id", "coach_contract_0001"),
        ("personId", "foreign-key", "person_coach_001"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("roleId", "foreign-key", "role_oc"),
        ("startSeasonId", "foreign-key", "season_2031"),
        ("endSeasonId", "foreign-key", "season_2033"),
        ("salary", "currency", "850000"),
        ("buyout", "currency", "300000"),
        ("status", "enum", "active"),
        ("responsibilityJson", "json", "{recruitingRegion:'TX'}"),
    ], parent="Coach Profile", layer="relationship/transaction", fm="FULL_CONTRACT/CONTRACT_OFFER pattern", basis="FM-derived architecture", phase="M3")
    sheets["Coach - Staff Model"] += rows_for("Staff Assignment", "staff_assignments", [
        ("assignmentId", "id", "staff_asg_0001"),
        ("coachContractId", "foreign-key", "coach_contract_0001"),
        ("assignmentType", "enum", "recruiting_region"),
        ("targetId", "foreign-key", "region_texas"),
        ("priority", "integer 1-5", "4"),
        ("startWeekId", "foreign-key", "week_2031_01"),
        ("endWeekId", "nullable foreign-key", ""),
    ], parent="Coach Contract", layer="relationship", fm="STAFFING_POLICY", basis="FM-derived architecture", phase="M4")

    # School/program.
    sheets["School - Program Model"] += rows_for("School", "schools", [
        ("schoolId", "id", "school_vanderbilt"),
        ("schoolName", "string", "Vanderbilt University"),
        ("shortName", "string", "Vanderbilt"),
        ("nickname", "string", "Commodores"),
        ("city", "string", "Nashville"),
        ("state", "enum", "TN"),
        ("regionId", "foreign-key", "region_southeast"),
        ("academicPrestige", "integer 1-100", "91"),
        ("campusAppeal", "integer 1-100", "82"),
        ("brandReach", "integer 1-100", "63"),
        ("tradition", "integer 1-100", "48"),
    ], fm="Static school/base database separated from save state", basis="planning-doc", phase="M0")
    sheets["School - Program Model"] += rows_for("Program", "programs", [
        ("programId", "id", "program_vanderbilt"),
        ("schoolId", "foreign-key", "school_vanderbilt"),
        ("sport", "enum", "football"),
        ("currentConferenceId", "foreign-key", "conf_sec"),
        ("prestige", "integer 1-100", "54"),
        ("fanConfidence", "integer 0-100", "62"),
        ("boosterSupport", "integer 0-100", "55"),
        ("mediaExpectation", "enum", "bowl_push"),
        ("playoffExpectation", "enum", "none"),
        ("coachTrust", "integer 0-100", "67"),
    ], parent="School", layer="world", fm="Program current state separated from school identity", basis="domain-design", phase="M0")
    sheets["School - Program Model"] += rows_for("Program Snapshot", "program_weekly_snapshots", [
        ("snapshotId", "id", "prog_snap_0001"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("wins", "integer", "2"),
        ("losses", "integer", "1"),
        ("conferenceWins", "integer", "0"),
        ("conferenceLosses", "integer", "0"),
        ("rank", "nullable integer", ""),
        ("offenseRating", "integer 1-100", "76"),
        ("defenseRating", "integer 1-100", "71"),
        ("specialTeamsRating", "integer 1-100", "69"),
        ("teamMorale", "integer 0-100", "70"),
        ("teamChemistry", "integer 0-100", "66"),
    ], parent="Program", layer="history/snapshot", fm="Weekly snapshots for long-term memory", basis="FM-derived architecture", phase="M2")

    # Calendar/year/conference/game.
    sheets["Years - Calendar Model"] += rows_for("Season", "seasons", [
        ("seasonId", "id", "season_2031"),
        ("year", "integer", "2031"),
        ("rulesetId", "foreign-key", "ruleset_modern_2026"),
        ("startDate", "date", "2031-01-01"),
        ("endDate", "date", "2031-12-31"),
        ("currentStatus", "enum", "active"),
    ], layer="calendar", fm="DATE_IN_YEAR and season boundary pattern", basis="FM-derived architecture", phase="M0")
    sheets["Years - Calendar Model"] += rows_for("Week", "weeks", [
        ("weekId", "id", "week_2031_04"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekNumber", "integer", "4"),
        ("phaseId", "foreign-key", "regular_season"),
        ("startDate", "date", "2031-09-15"),
        ("endDate", "date", "2031-09-21"),
        ("isAdvanceLocked", "boolean", "false"),
        ("requiredDecisionCount", "integer", "1"),
    ], parent="Season", layer="calendar", fm="Rule-driven week/phase calendar", basis="FM-derived architecture", phase="M0")
    sheets["Years - Calendar Model"] += rows_for("Calendar Event", "calendar_events", [
        ("calendarEventId", "id", "cal_0001"),
        ("eventTypeId", "foreign-key", "evt_visit_weekend"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("date", "date", "2031-09-19"),
        ("status", "enum", "scheduled"),
        ("subjectType", "enum", "recruit"),
        ("subjectId", "foreign-key", "person_2032_000234"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("blocksAdvance", "boolean", "false"),
        ("resultEventId", "nullable foreign-key", ""),
    ], layer="calendar", fm="TEAM_FUTURE_FIXTURE/deadlines/windows", basis="FM-derived architecture", phase="M2")
    sheets["Years - Calendar Model"] += rows_for("Action Window", "action_windows", [
        ("windowId", "id", "window_recruiting_contact_2031_01"),
        ("rulesetId", "foreign-key", "ruleset_modern_2026"),
        ("windowType", "enum", "recruiting_contact"),
        ("startWeekId", "foreign-key", "week_2031_01"),
        ("endWeekId", "foreign-key", "week_2031_12"),
        ("allowedActionIds", "array<foreign-key>", "contact_recruit,offer_scholarship"),
        ("restrictionNotes", "text", ""),
    ], layer="ruleset/calendar", fm="TRANSFER_WINDOW/TRANSFER_DEADLINE_DAY analogue", basis="FM-derived architecture", phase="M3")

    sheets["Conference - Competition Model"] += rows_for("Conference", "conferences", [
        ("conferenceId", "id", "conf_sec"),
        ("name", "string", "Southeastern Conference"),
        ("shortName", "string", "SEC"),
        ("tier", "enum", "P4"),
        ("prestige", "integer 1-100", "92"),
        ("mediaDealStrength", "integer 1-100", "95"),
        ("playoffAccess", "enum", "auto_possible"),
    ], layer="definition/world", fm="Competition database/rule-group pattern", basis="FM-derived architecture", phase="M0")
    sheets["Conference - Competition Model"] += rows_for("Conference Membership", "conference_memberships", [
        ("membershipId", "id", "conf_mem_0001"),
        ("conferenceId", "foreign-key", "conf_sec"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("startSeasonId", "foreign-key", "season_2031"),
        ("endSeasonId", "nullable foreign-key", ""),
        ("divisionId", "nullable foreign-key", ""),
        ("podId", "nullable foreign-key", ""),
        ("status", "enum", "active"),
    ], parent="Conference", layer="relationship", fm="Parent/child competition links and memberships", basis="FM-derived architecture", phase="M1")
    sheets["Conference - Competition Model"] += rows_for("Competition Rule", "competition_rules", [
        ("competitionRuleId", "id", "comp_rule_sec_2031"),
        ("conferenceId", "foreign-key", "conf_sec"),
        ("rulesetId", "foreign-key", "ruleset_modern_2026"),
        ("conferenceGames", "integer", "8"),
        ("championshipFormat", "enum", "top_two"),
        ("tiebreakerRuleId", "foreign-key", "tiebreaker_sec_v1"),
        ("scheduleRuleId", "foreign-key", "sched_sec_v1"),
        ("revenueShareModel", "enum", "equal"),
    ], parent="Conference", layer="ruleset", fm="Fixture rules/sorting rules/team count data", basis="FM-derived architecture", phase="M3")

    sheets["Game - Schedule Model"] += rows_for("Scheduled Game", "scheduled_games", [
        ("gameId", "id", "game_2031_0042"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("homeProgramId", "foreign-key", "program_vanderbilt"),
        ("awayProgramId", "foreign-key", "program_kentucky"),
        ("siteType", "enum", "home"),
        ("stadiumId", "foreign-key", "stadium_vandy"),
        ("kickoffTime", "datetime", "2031-09-20T19:30:00"),
        ("isConferenceGame", "boolean", "true"),
        ("isRivalryGame", "boolean", "false"),
        ("tvNetworkId", "nullable foreign-key", "network_sec"),
        ("status", "enum", "scheduled"),
    ], layer="calendar/world", fm="FIXTURE/TEAM_FUTURE_FIXTURE/FIXTURE_TO_PLAY", basis="FM-derived architecture", phase="M2")
    sheets["Game - Schedule Model"] += rows_for("Game Result", "game_results", [
        ("resultId", "id", "result_0001"),
        ("gameId", "foreign-key", "game_2031_0042"),
        ("homeScore", "integer", "27"),
        ("awayScore", "integer", "24"),
        ("quarterScoresJson", "json", ""),
        ("winnerProgramId", "foreign-key", "program_vanderbilt"),
        ("playedAt", "datetime", ""),
        ("simRunId", "foreign-key", "simrun_0001"),
        ("resultSummaryEventId", "foreign-key", "event_0044"),
    ], parent="Scheduled Game", layer="history", fm="FIXTURE_RESULT/FIXTURE_RECORD", basis="FM-derived architecture", phase="M5")
    sheets["Game - Schedule Model"] += rows_for("Player Game Stat", "player_game_stats", [
        ("statLineId", "id", "pgs_0001"),
        ("gameId", "foreign-key", "game_2031_0042"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("positionId", "foreign-key", "pos_qb"),
        ("statCategory", "enum", "passing"),
        ("statsJson", "json", "{yards:244,td:2,int:1}"),
    ], parent="Game Result", layer="history/stat", fm="PLAYER_STATS_HISTORY", basis="FM-derived architecture", phase="M5")

    # Schemes/playbooks/rules/resources.
    sheets["Schemes - Playbooks Model"] += rows_for("Scheme Definition", "scheme_definitions", [
        ("schemeId", "id", "scheme_spread_option"),
        ("sideOfBall", "enum", "offense"),
        ("name", "string", "Spread Option"),
        ("description", "text", ""),
        ("requiredSkillWeightsJson", "json", ""),
        ("preferredPersonnelGroups", "array<foreign-key>", "11,10"),
        ("riskProfile", "enum", "medium"),
    ], layer="definition", fm="Tactical training/squad role data as definitions", basis="planning-doc", phase="M2")
    sheets["Schemes - Playbooks Model"] += rows_for("Play Concept", "play_concepts", [
        ("conceptId", "id", "concept_inside_zone_glance"),
        ("schemeId", "foreign-key", "scheme_spread_option"),
        ("playType", "enum", "RPO"),
        ("formationFamilyId", "foreign-key", "formation_trips"),
        ("personnelGroupId", "foreign-key", "personnel_11"),
        ("stressedDefender", "enum", "apex"),
        ("requiredSkillsJson", "json", "{QB.processing:high}"),
        ("countersJson", "json", ""),
        ("situationFitJson", "json", ""),
    ], parent="Scheme Definition", layer="definition", fm="Tactical training data plus play resolver needs", basis="planning-doc", phase="M5")
    sheets["Rulesets Model"] += rows_for("Ruleset", "rulesets", [
        ("rulesetId", "id", "ruleset_modern_2026"),
        ("name", "string", "Modern College Football"),
        ("version", "integer", "1"),
        ("baseYear", "integer", "2026"),
        ("calendarRuleId", "foreign-key", "calendar_modern_2026"),
        ("rosterRuleId", "foreign-key", "roster_fbs_85"),
        ("eligibilityRuleId", "foreign-key", "eligibility_ncaa_v1"),
        ("nilRuleId", "foreign-key", "nil_modern_v1"),
        ("transferRuleId", "foreign-key", "portal_modern_v1"),
        ("postseasonRuleId", "foreign-key", "cfp_12_v1"),
    ], layer="ruleset", fm="Fixture/squad/transfer/rule data versioning", basis="FM-derived architecture", phase="M0")
    sheets["Rulesets Model"] += rows_for("Rule Constraint", "rule_constraints", [
        ("constraintId", "id", "constraint_scholarship_max"),
        ("rulesetId", "foreign-key", "ruleset_modern_2026"),
        ("constraintType", "enum", "roster_limit"),
        ("subjectType", "enum", "program"),
        ("field", "string", "scholarshipCount"),
        ("operator", "enum", "less_or_equal"),
        ("value", "number", "85"),
        ("severity", "enum", "blocker"),
    ], parent="Ruleset", layer="ruleset/invariant", fm="SQUAD_SELECTION_RULES analogue", basis="FM-derived architecture", phase="M1")

    # Relationship, history, transaction, scouting, NIL, facilities, events, sim, resources.
    sheets["Relationship Tables"] += rows_for("Depth Chart Assignment", "depth_chart_assignments", [
        ("assignmentId", "id", "dc_0001"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekId", "foreign-key", "week_2031_04"),
        ("positionId", "foreign-key", "pos_qb"),
        ("slot", "integer", "1"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("status", "enum", "active"),
    ], layer="relationship", fm="Squad selection/lineup as records", basis="FM-derived architecture", phase="M2")
    sheets["Relationship Tables"] += rows_for("Program Rivalry", "program_rivalries", [
        ("rivalryId", "id", "rivalry_vandy_tennessee"),
        ("programAId", "foreign-key", "program_vanderbilt"),
        ("programBId", "foreign-key", "program_tennessee"),
        ("rivalryName", "string", ""),
        ("intensity", "integer 1-100", "72"),
        ("protectedGame", "boolean", "true"),
        ("startSeasonId", "foreign-key", "season_1900"),
    ], layer="relationship", fm="RIVALRY", basis="FM-derived architecture", phase="M3")
    sheets["Relationship Tables"] += rows_for("Scholarship Allocation", "scholarship_allocations", [
        ("scholarshipId", "id", "sch_0001"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("personId", "foreign-key", "person_2032_000234"),
        ("seasonId", "foreign-key", "season_2031"),
        ("status", "enum", "offered"),
        ("offerWeekId", "foreign-key", "week_2031_04"),
        ("acceptedWeekId", "nullable foreign-key", ""),
    ], layer="relationship/transaction", fm="CONTRACT_OFFER analogue for scholarships", basis="domain-design", phase="M3")

    sheets["History - Snapshot Tables"] += rows_for("Person History", "person_history", [
        ("historyId", "id", "hist_0001"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("historyType", "enum", "joined_program"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekId", "foreign-key", "week_2031_01"),
        ("programId", "nullable foreign-key", "program_vanderbilt"),
        ("relatedObjectType", "nullable enum", "scholarship"),
        ("relatedObjectId", "nullable id", "sch_0001"),
        ("summary", "text", ""),
        ("sourceEventId", "foreign-key", "event_0001"),
    ], layer="history", fm="PERSON_HISTORY/PLAYING_HISTORY", basis="FM-derived architecture", phase="M2")
    sheets["History - Snapshot Tables"] += rows_for("History Index", "history_indexes", [
        ("indexId", "id", "hist_idx_0001"),
        ("historyId", "foreign-key", "hist_0001"),
        ("subjectType", "enum", "person"),
        ("subjectId", "id", "person_2031_000123"),
        ("programId", "nullable foreign-key", "program_vanderbilt"),
        ("seasonId", "foreign-key", "season_2031"),
        ("weekId", "foreign-key", "week_2031_01"),
        ("eventTypeId", "foreign-key", "joined_program"),
    ], parent="Person History", layer="index", fm="history id/index/data split", basis="FM-derived architecture", phase="M2")
    sheets["Transactions Model"] += rows_for("Transaction", "transactions", [
        ("transactionId", "id", "txn_0001"),
        ("transactionType", "enum", "scholarship_offer"),
        ("status", "enum", "active"),
        ("sourceProgramId", "nullable foreign-key", "program_vanderbilt"),
        ("targetPersonId", "nullable foreign-key", "person_2032_000234"),
        ("amount", "nullable currency", ""),
        ("createdWeekId", "foreign-key", "week_2031_04"),
        ("resolvedWeekId", "nullable foreign-key", ""),
        ("failureReasonId", "nullable foreign-key", ""),
    ], layer="transaction", fm="active/completed/failed offers and negotiations", basis="FM-derived architecture", phase="M3")
    sheets["Transactions Model"] += rows_for("Future Move", "future_moves", [
        ("futureMoveId", "id", "move_0001"),
        ("personId", "foreign-key", "person_2032_000234"),
        ("fromProgramId", "nullable foreign-key", ""),
        ("toProgramId", "foreign-key", "program_vanderbilt"),
        ("moveType", "enum", "signed_recruit"),
        ("effectiveWeekId", "foreign-key", "week_2032_01"),
        ("transactionId", "foreign-key", "txn_0001"),
        ("status", "enum", "pending"),
    ], parent="Transaction", layer="transaction/calendar", fm="STARTING_FUTURE_TRANSFER", basis="FM-derived architecture", phase="M4")

    sheets["Scouting - Knowledge Model"] += rows_for("Scouting Report", "scouting_reports", [
        ("reportId", "id", "scout_0001"),
        ("subjectType", "enum", "person"),
        ("subjectId", "foreign-key", "person_2032_000234"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("scoutCoachId", "foreign-key", "coach_004"),
        ("createdWeekId", "foreign-key", "week_2031_04"),
        ("freshness", "integer 0-100", "92"),
        ("overallGrade", "string", "B+"),
        ("certainty", "integer 0-100", "41"),
        ("biasProfileId", "foreign-key", "bias_qb_arm_strength"),
        ("summaryTemplateId", "foreign-key", "scout_summary_qb_v1"),
    ], layer="scouting/knowledge", fm="SCOUTED_PERSON/SCOUTED_TEAM_INFO", basis="FM-derived architecture", phase="M3")
    sheets["Scouting - Knowledge Model"] += rows_for("Knowledge Snapshot", "knowledge_snapshots", [
        ("knowledgeSnapshotId", "id", "know_0001"),
        ("reportId", "foreign-key", "scout_0001"),
        ("fieldPath", "string", "ratings.throwPower"),
        ("estimatedLow", "number", "72"),
        ("estimatedHigh", "number", "86"),
        ("trueValueVisible", "boolean", "false"),
        ("confidence", "integer 0-100", "45"),
    ], parent="Scouting Report", layer="snapshot", fm="Attribute snapshots with certainty", basis="FM-derived architecture", phase="M3")

    sheets["NIL - Finance Model"] += rows_for("Program Finance", "program_finances", [
        ("financeId", "id", "finance_vandy_2031"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("seasonId", "foreign-key", "season_2031"),
        ("athleticBudget", "currency", "42000000"),
        ("recruitingBudget", "currency", "3000000"),
        ("staffBudget", "currency", "6500000"),
        ("nilBudget", "currency", "4500000"),
        ("monthlyIncome", "currency", "510000"),
        ("monthlyExpenses", "currency", "390000"),
    ], layer="world/finance", fm="CLUB_FINANCE analogue", basis="FM-derived architecture", phase="M3")
    sheets["NIL - Finance Model"] += rows_for("NIL Deal", "nil_deals", [
        ("nilDealId", "id", "nil_0001"),
        ("personId", "foreign-key", "person_2031_000123"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("collectiveId", "foreign-key", "collective_vandy"),
        ("annualValue", "currency", "45000"),
        ("status", "enum", "active"),
        ("riskScore", "integer 0-100", "18"),
        ("startWeekId", "foreign-key", "week_2031_01"),
        ("endWeekId", "nullable foreign-key", ""),
    ], parent="Person", layer="relationship/finance", fm="Money-like changes as transactions", basis="planning-doc", phase="M4")

    sheets["Facilities - Brand Model"] += rows_for("School Brand", "school_brands", [
        ("brandId", "id", "brand_vandy"),
        ("schoolId", "foreign-key", "school_vanderbilt"),
        ("primaryColor", "color", "#000000"),
        ("secondaryColor", "color", "#A28D5B"),
        ("accentColor", "color", "#FFFFFF"),
        ("logoAssetId", "foreign-key", "asset_logo_vandy"),
        ("wordmarkAssetId", "foreign-key", "asset_wordmark_vandy"),
        ("numberFontId", "foreign-key", "font_block_serif"),
        ("stripePatternId", "foreign-key", "stripe_classic"),
    ], parent="School", layer="definition/resource", fm="Static resource/overlay data", basis="planning-doc", phase="M1")
    sheets["Facilities - Brand Model"] += rows_for("Stadium", "stadiums", [
        ("stadiumId", "id", "stadium_vandy"),
        ("schoolId", "foreign-key", "school_vanderbilt"),
        ("name", "string", "FirstBank Stadium"),
        ("capacity", "integer", "40143"),
        ("surfaceType", "enum", "grass"),
        ("atmosphere", "integer 1-100", "56"),
        ("homeFieldAdvantage", "integer 1-100", "52"),
        ("noiseRating", "integer 1-100", "47"),
        ("expansionPotential", "integer 1-100", "35"),
    ], parent="School", layer="world/facility", fm="STADIUM_DATE/resource pattern", basis="planning-doc", phase="M4")
    sheets["Facilities - Brand Model"] += rows_for("Uniform Set", "uniform_sets", [
        ("uniformSetId", "id", "uniform_vandy_home_2031"),
        ("schoolId", "foreign-key", "school_vanderbilt"),
        ("seasonId", "foreign-key", "season_2031"),
        ("setType", "enum", "home"),
        ("helmetColor", "color", "#000000"),
        ("jerseyColor", "color", "#000000"),
        ("pantsColor", "color", "#FFFFFF"),
        ("numberColor", "color", "#A28D5B"),
        ("decalAssetId", "foreign-key", "asset_v_logo"),
    ], parent="School Brand", layer="resource", fm="Patchable visual/resource definition", basis="planning-doc", phase="M4")

    sheets["Events - Inbox - News Model"] += rows_for("Event Log", "event_log", [
        ("eventId", "id", "event_0001"),
        ("eventTypeId", "foreign-key", "evt_recruit_interest_shift"),
        ("category", "enum", "recruiting"),
        ("priority", "enum", "normal"),
        ("createdWeekId", "foreign-key", "week_2031_04"),
        ("subjectType", "enum", "recruit"),
        ("subjectId", "foreign-key", "person_2032_000234"),
        ("actorJson", "json", "{programId:'program_vanderbilt'}"),
        ("sourceActionId", "nullable foreign-key", "action_0001"),
        ("visibility", "enum", "user_program"),
        ("resolved", "boolean", "false"),
    ], layer="event/log", fm="EVENT and report/news routing pattern", basis="FM-derived architecture", phase="M0")
    sheets["Events - Inbox - News Model"] += rows_for("Inbox Item", "inbox_items", [
        ("inboxItemId", "id", "inbox_0001"),
        ("eventId", "foreign-key", "event_0001"),
        ("programId", "foreign-key", "program_vanderbilt"),
        ("assignedToRoleId", "nullable foreign-key", "role_head_coach"),
        ("status", "enum", "unread"),
        ("blocksAdvance", "boolean", "false"),
        ("dueWeekId", "nullable foreign-key", ""),
        ("primaryActionId", "foreign-key", "action_open_recruit"),
    ], parent="Event Log", layer="event/ui", fm="Events become inbox/news/report channels", basis="FM-derived architecture", phase="M2")
    sheets["Events - Inbox - News Model"] += rows_for("News Item", "news_items", [
        ("newsItemId", "id", "news_0001"),
        ("eventId", "foreign-key", "event_0001"),
        ("scope", "enum", "conference"),
        ("headlineTemplateId", "foreign-key", "headline_recruit_commit"),
        ("bodyTemplateId", "foreign-key", "body_recruit_commit"),
        ("publishedWeekId", "foreign-key", "week_2031_04"),
        ("relatedObjectRefJson", "json", ""),
    ], parent="Event Log", layer="event/media", fm="Report variants tied to events", basis="FM-derived architecture", phase="M3")

    sheets["Simulation Engine Model"] += rows_for("Simulation Run", "simulation_runs", [
        ("simRunId", "id", "simrun_0001"),
        ("runType", "enum", "game"),
        ("seed", "string", "sim-2031-0042"),
        ("rulesetId", "foreign-key", "ruleset_modern_2026"),
        ("startedAt", "datetime", ""),
        ("completedAt", "datetime", ""),
        ("status", "enum", "complete"),
        ("invariantSummaryJson", "json", ""),
    ], layer="simulation/log", fm="Headless/debug world sim affordances", basis="FM-derived architecture", phase="M3")
    sheets["Simulation Engine Model"] += rows_for("Play Event", "play_events", [
        ("playEventId", "id", "play_0001"),
        ("gameId", "foreign-key", "game_2031_0042"),
        ("driveId", "foreign-key", "drive_0001"),
        ("quarter", "integer", "1"),
        ("clock", "string", "12:44"),
        ("down", "integer", "2"),
        ("distance", "integer", "7"),
        ("fieldPosition", "integer", "38"),
        ("offenseProgramId", "foreign-key", "program_vanderbilt"),
        ("defenseProgramId", "foreign-key", "program_kentucky"),
        ("personnelGroupId", "foreign-key", "personnel_11"),
        ("formationId", "foreign-key", "formation_trips"),
        ("conceptId", "foreign-key", "concept_inside_zone_glance"),
        ("defensiveCallId", "foreign-key", "def_call_quarters"),
        ("yardsGained", "integer", "14"),
        ("resultType", "enum", "complete_pass"),
        ("explanation", "text", ""),
    ], parent="Simulation Run", layer="simulation/history", fm="Match event tables with probability/explanation hooks", basis="planning-doc", phase="M5")
    sheets["Simulation Engine Model"] += rows_for("Play Conflict", "play_conflicts", [
        ("conflictId", "id", "conflict_0001"),
        ("playEventId", "foreign-key", "play_0001"),
        ("conflictType", "enum", "apex_read"),
        ("offensePersonId", "nullable foreign-key", "person_2031_000123"),
        ("defensePersonId", "nullable foreign-key", "person_2031_000987"),
        ("relevantAttributeIds", "array<foreign-key>", "processing,eye_discipline"),
        ("winProbability", "number", "0.58"),
        ("winnerSide", "enum", "offense"),
        ("creditBlameJson", "json", ""),
    ], parent="Play Event", layer="simulation/history", fm="Sim decisive conflicts, not 22 full agents first", basis="planning-doc", phase="M5")

    sheets["Resources - UI Contracts"] += rows_for("Workspace Definition", "workspace_definitions", [
        ("workspaceId", "id", "roster"),
        ("objectType", "enum", "program"),
        ("defaultRoute", "string", "/program/:programId/roster"),
        ("primaryTableDefinitionId", "foreign-key", "table_roster_players"),
        ("tabIds", "array<foreign-key>", "overview,depth_chart,development"),
        ("actionIds", "array<foreign-key>", "open_player,set_development_focus"),
        ("inspectorDefinitionId", "foreign-key", "inspector_player_summary"),
    ], layer="resource/ui", fm="FM panels/menus/actions/resources", basis="FM-derived architecture", phase="M0")
    sheets["Resources - UI Contracts"] += rows_for("Action Definition", "action_definitions", [
        ("actionId", "id", "set_development_focus"),
        ("label", "string", "Set Development Focus"),
        ("subjectType", "enum", "player"),
        ("commandType", "enum", "SET_PLAYER_DEVELOPMENT_FOCUS"),
        ("enabledWhenJson", "json", ""),
        ("writesJson", "json", "player_development_plans,action_log,event_log"),
        ("visibleInWorkspaceIds", "array<foreign-key>", "roster,player_profile"),
        ("iconId", "foreign-key", "cfl-practice"),
    ], layer="resource/action", fm="Action registry/menu event IDs", basis="FM-derived architecture", phase="M0")
    sheets["Resources - UI Contracts"] += rows_for("Column Definition", "column_definitions", [
        ("columnId", "id", "player_overall"),
        ("entityType", "enum", "player"),
        ("label", "string", "OVR"),
        ("valueSelector", "string", "latestRating.overall"),
        ("format", "enum", "integer"),
        ("sortable", "boolean", "true"),
        ("filterable", "boolean", "true"),
        ("visibleByDefault", "boolean", "true"),
    ], layer="resource/ui", fm="Reusable property/table resource pattern", basis="FM-derived architecture", phase="M0")

    # Enums.
    enum_values = {
        "PersonRoleType": ["athlete", "recruit", "coach", "staff", "created_person"],
        "Position": ["QB", "RB", "WR", "TE", "OT", "OG", "C", "EDGE", "DL", "LB", "CB", "S", "K", "P", "LS", "ATH"],
        "PlayerClass": ["FR", "SO", "JR", "SR", "RS-FR", "RS-SO", "RS-JR", "RS-SR"],
        "SeasonPhase": ["offseason", "spring_practice", "summer_recruiting", "preseason", "regular_season", "rivalry_week", "conference_championship", "postseason", "signing_window", "portal_window", "winter_development"],
        "RecruitStatus": ["open", "verbal_commit", "soft_verbal", "signed", "decommitted", "withdrawn"],
        "TransactionStatus": ["draft", "active", "accepted", "rejected", "withdrawn", "failed", "completed", "expired"],
        "EventCategory": ["roster", "recruiting", "game", "staff", "nil", "finance", "injury", "development", "media", "rules"],
        "ActionWindowType": ["recruiting_contact", "official_visit", "portal_entry", "staff_hiring", "depth_chart_lock", "game_plan_lock"],
        "EntityLayer": ["world", "facet", "relationship", "history", "snapshot", "transaction", "definition", "resource", "ruleset", "event", "simulation"],
    }
    for enum_name, values in enum_values.items():
        for value in values:
            sheets["Enums - Value Lists"].append(row(enum_name, "enum_values", value, "enum-value", value, parent=enum_name, layer="definition", fm="Versioned static vocabulary", basis="domain-design", phase="M0"))

    # Entity index derived from sheet rows plus explicit core entities.
    entity_defs = [
        ("Person", "core entity", "Base human identity for players, recruits, coaches, staff, and created people.", "", "people", "athlete_profiles, recruiting_profiles, coach_profiles", "people/basic people split", "M0"),
        ("Athlete Profile", "facet", "Football/body/current ability facet attached to Person.", "Person", "athlete_profiles", "player_rating_snapshots, roster_memberships", "live player record plus snapshots", "M1"),
        ("Recruiting Profile", "facet", "Recruiting lifecycle facet attached to a Person.", "Person", "recruiting_profiles", "recruit_program_interest, official_visits, scholarship_allocations", "scouted person and offers", "M3"),
        ("Coach Profile", "facet", "Non-player football staff identity attached to Person.", "Person", "coach_profiles", "coach_program_contracts, staff_assignments", "non-player profile/history split", "M2"),
        ("School", "core entity", "Static institution identity.", "", "schools", "programs, school_brands, stadiums", "base database record", "M0"),
        ("Program", "core entity", "Football program state for a school.", "School", "programs", "memberships, schedule, finances, snapshots", "club/team current state", "M0"),
        ("Conference", "core entity", "Competition container and membership/rule source.", "", "conferences", "conference_memberships, competition_rules", "competition hierarchy/rules", "M1"),
        ("Season", "core entity", "Yearly world container.", "", "seasons", "weeks, games, rulesets", "date/season boundary records", "M0"),
        ("Week", "core entity", "Advance unit and action availability boundary.", "Season", "weeks", "calendar_events, action_windows", "calendar phase system", "M0"),
        ("Game", "core entity", "Scheduled and completed football contest.", "Week", "scheduled_games", "game_results, play_events, stats", "fixture/result split", "M2"),
        ("Ruleset", "definition/rules", "Versioned game law and constraints.", "", "rulesets", "rule_constraints, windows, competition_rules", "fixture/squad/transfer rules", "M0"),
        ("Scheme", "definition", "Football tactical vocabulary and skill fit definitions.", "", "scheme_definitions", "play_concepts, coach_profiles", "tactical training data", "M2"),
        ("Event", "event/log", "Durable fact emitted by action or simulation.", "", "event_log", "inbox_items, news_items, histories", "EVENT/report routing", "M0"),
        ("Transaction", "transaction", "Offer, negotiation, money, move, or pending future change.", "", "transactions", "future_moves, contracts, scholarships, NIL", "active/completed/failed transfer offer stores", "M3"),
        ("History", "history/index", "Append-only long-term memory and query index.", "", "person_history", "history_indexes, snapshots", "history id/index/data split", "M2"),
        ("UI Resource", "resource", "Workspace/action/column/menu contract.", "", "workspace_definitions", "action_definitions, column_definitions", "actions/menus/panels/resources", "M0"),
    ]
    for item in entity_defs:
        sheets["Entity Index"].append(list(item) + ["Review table rows before approval.", "pending-review"])

    sheets["Implementation Milestones"] = [
        ["M0", "New project skeleton and domain contracts, no feature breadth.", "world_saves, people, schools, programs, seasons, weeks, rulesets, event_log, resources", "object-router, action registry, basic selectors", "save/load roundtrip, no dangling IDs, one object click path", "pending-review"],
        ["M1", "Start Career creates a real minimum world.", "athlete_profiles, roster_memberships, school_brands, conference_memberships", "world factory, program desk selector", "new career creates IDs/relations; save reloads same state", "pending-review"],
        ["M2", "Player/person object loop.", "rating snapshots, weekly state, depth chart assignments, person_history", "roster selector, profile selector, set development focus", "action writes log/history and selector refreshes", "pending-review"],
        ["M3", "Recruiting and calendar slice.", "recruiting_profiles, recruit_program_interest, scouting_reports, transactions, action_windows", "scout/contact/offer/schedule visit actions", "calendar/inbox/recruit profile all read same records", "pending-review"],
        ["M4", "Preseason systems.", "official_visits, promises, staff assignments, NIL deals, stadium/uniform/facility data", "advance week with blockers/windows", "phase rules and invariants gate Continue", "pending-review"],
        ["M5", "First game slice.", "scheduled_games, game_results, play_events, play_conflicts, player_game_stats", "game preview, sim runner, postgame selectors", "result appears on schedule/program/player histories", "pending-review"],
    ]

    sheets["Quality Gates"] = [
        ["Schema validation", "All tables", "Every record validates against schema and required FK fields.", "Model is not safe to implement.", "zod/drizzle validation", "pending-review"],
        ["No dangling IDs", "Relationships/history/transactions", "Every foreign key resolves or is explicitly nullable.", "Clickthrough and history will break.", "invariant test", "pending-review"],
        ["Action log writes", "Actions", "Every command writes an action log record.", "The game cannot explain user decisions.", "action unit tests", "pending-review"],
        ["Event provenance", "Inbox/news/history", "Every inbox/news/history row has source event or source action.", "UI can invent fake text again.", "event invariant", "pending-review"],
        ["Save/load roundtrip", "World save", "Serialized save reloads equal IDs, relations, ruleset, current route.", "Persistence cannot be trusted.", "roundtrip test", "pending-review"],
        ["World tick contract", "Calendar/advanceWeek", "Each tick returns state patch, events, history, metrics, warnings.", "Continue will become random mutation.", "scenario runner", "pending-review"],
        ["Rating distribution bounds", "Player generation/development", "Ratings stay within ruleset bands over 20-year soak.", "Future sims get wild.", "soak test", "pending-review"],
        ["UI resource coverage", "Workspaces", "Visible buttons/tables map to action/column/workspace definitions.", "Clickthrough will be inconsistent.", "static UI contract test", "pending-review"],
        ["Screen selector purity", "Selectors", "Selectors do not mutate world state.", "Screens become sources of truth.", "unit tests", "pending-review"],
    ]

    sheets["Open Questions"] = [
        ["Should Coach and Staff be separate profile facets or one non-player profile with role definitions?", "coach_profiles, staff_assignments", "Affects hiring/staff carousel shape.", "Use Person + CoachProfile + role/assignment tables.", "Before M2", "pending-review"],
        ["Should recruits become athlete_profiles immediately or only after enrollment?", "recruiting_profiles, athlete_profiles", "Affects true ratings and profile pages.", "Create Person + AthleteProfile early, gate roster membership until enrollment.", "Before M3", "pending-review"],
        ["How much true rating data should exist before scouting?", "rating snapshots, knowledge snapshots", "Affects generation and scouting uncertainty.", "Always generate true ratings; expose only knowledge snapshots.", "Before M3", "pending-review"],
        ["Should real schools be base data or optional content pack?", "schools, programs", "Legal/modding/product direction.", "Keep schema neutral; load school packs separately.", "Before content build", "pending-review"],
        ["How strict should first ruleset be about NCAA details?", "rulesets, constraints", "Complexity vs realism.", "Create simplified modern ruleset with explicit version.", "Before M1", "pending-review"],
        ["What is the initial database target?", "all tables", "Static JSON vs SQLite affects implementation.", "Prototype with TypeScript schemas and JSON seed, design table names as SQLite-ready.", "Before coding new game", "pending-review"],
    ]

    return sheets


def headers_for(sheet):
    if sheet == "README":
        return ["Topic", "Details"]
    if sheet == "Architecture Principles":
        return PRINCIPLE_HEADERS
    if sheet == "Entity Index":
        return ENTITY_INDEX_HEADERS
    if sheet == "Implementation Milestones":
        return MILESTONE_HEADERS
    if sheet == "Quality Gates":
        return QUALITY_HEADERS
    if sheet == "Open Questions":
        return OPEN_HEADERS
    if sheet == "Change Log":
        return CHANGE_HEADERS
    return FIELD_HEADERS


def safe_csv_name(sheet):
    return re.sub(r"[^A-Za-z0-9]+", "_", sheet).strip("_").lower() + ".csv"


def style_sheet(ws):
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1F2937")
        cell.alignment = Alignment(wrap_text=True, vertical="top")
    for row_cells in ws.iter_rows(min_row=2):
        for cell in row_cells:
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    for idx, col in enumerate(ws.columns, 1):
        max_len = 0
        for cell in col:
            max_len = max(max_len, min(len("" if cell.value is None else str(cell.value)), 70))
        ws.column_dimensions[get_column_letter(idx)].width = max(12, min(44, max_len + 2))
    headers = [c.value for c in ws[1]]
    for header, colors in [("Source Basis", SOURCE_COLORS), ("Approval Status", APPROVAL_COLORS)]:
        if header in headers:
            col = get_column_letter(headers.index(header) + 1)
            for value, color in colors.items():
                ws.conditional_formatting.add(
                    f"{col}2:{col}{max(ws.max_row, 2)}",
                    FormulaRule(formula=[f'{col}2="{value}"'], fill=PatternFill("solid", fgColor=color)),
                )


def repo_commit():
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return ""


def write_outputs(sheets):
    now = datetime.now().isoformat(timespec="seconds")
    sources = [
        "docs/START_HERE.md",
        "docs/BUILD_PLAN.md",
        "docs/PROJECT_STATUS.md",
        "docs/archive/2026-05-pre-rebuild-research/CGM_DOMAIN_RESOURCE_ARCHITECTURE.md",
        "docs/archive/2026-05-pre-rebuild-research/FM_SAVE_DEEP_SCAN_REPORT.md",
        "docs/archive/2026-05-pre-rebuild-research/FM_SAVE_PASS3_CGM_GAP_AUDIT.md",
        "docs/archive/2026-05-pre-rebuild-research/FM_SAVE_PASS4_DOMAIN_SPINE_IMPLEMENTATION_PLAN.md",
        "docs/archive/2026-05-pre-rebuild-research/FM2020_OVERLAP_FEATURE_CATALOG.md",
        "ai-pack/CFB_FM_BUILD_SUPERPACK/08_DATA_MODELS_V1.md",
        "ai-pack/CFB_FM_BUILD_SUPERPACK/02_ENGINE_ARCHITECTURE_SPEC.md",
        "ai-pack/CFB_FM_CORE_SYSTEMS_BLOWOUT.md",
        "ai-pack/24_TRAIT_ARCHETYPES_CREATORS_AND_ADVANCED_IDENTITY_SYSTEMS.md",
        "ai-pack/football_sim_engine_realism_roadmap.md",
    ]
    sheets["README"] = [
        ["Date generated", now],
        ["Repo path inspected", str(ROOT)],
        ["Purpose", "Proposed future data model inventory for a new independent College Football Legends game, informed by planning docs and FM-derived architecture research."],
        ["Important scope note", "This is not current-code inventory and does not implement game functionality."],
        ["How to read Logical Entity", "Top-level product concept such as Person, Program, Season, Event, Transaction, or Ruleset."],
        ["How to read Table / Store", "Concrete proposed table/store name. Facets and relationship tables are intentionally separate from core entities."],
        ["How to read Entity Layer", "world, facet, relationship, history, snapshot, transaction, definition, resource, ruleset, event, or simulation."],
        ["How to read FM-Inspired Pattern", "Architecture-level pattern derived from FM research, not copied schema/content."],
        ["How to read Source Basis", "FM-derived architecture, planning-doc, domain-design, current-overlap, or recommended."],
        ["Approval Status", "All rows default to pending-review for human approval/rejection/revision."],
        ["Sources reviewed", "; ".join(sources)],
        ["Next step", "Review Entity Index first, then approve/revise table groups before any new-game coding starts."],
    ]
    sheets["Change Log"] = [[datetime.now().date().isoformat(), "Generated proposed data model inventory.", "Planning artifact only; no app code changed.", "Codex", repo_commit()]]

    OUT_CSV_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_CSV_DIR.glob("*.csv"):
        old.unlink()
    for sheet in SHEETS:
        with open(OUT_CSV_DIR / safe_csv_name(sheet), "w", newline="", encoding="utf-8-sig") as f:
            writer = csv.writer(f)
            writer.writerow(headers_for(sheet))
            rows = sheets.get(sheet, [])
            if rows:
                writer.writerows(rows)
            else:
                writer.writerow(["No current proposed fields found"])

    wb = Workbook()
    wb.remove(wb.active)
    for sheet in SHEETS:
        ws = wb.create_sheet(sheet)
        ws.append(headers_for(sheet))
        rows = sheets.get(sheet, [])
        if rows:
            for r in rows:
                ws.append(r)
        else:
            ws.append(["No current proposed fields found"])
        style_sheet(ws)
    wb.save(OUT_XLSX)


def verify():
    wb = load_workbook(OUT_XLSX, read_only=True)
    return {
        "exists": OUT_XLSX.exists(),
        "sheet_count": len(wb.sheetnames),
        "missing_sheets": [s for s in SHEETS if s not in wb.sheetnames],
        "bad_headers": [s for s in wb.sheetnames if not wb[s].cell(1, 1).value],
        "csv_count": len(list(OUT_CSV_DIR.glob("*.csv"))),
    }


def main():
    sheets = build_model()
    write_outputs(sheets)
    verification = verify()
    field_rows = sum(len(sheets[s]) for s in SHEETS if s not in {"README", "Architecture Principles", "Entity Index", "Implementation Milestones", "Quality Gates", "Open Questions", "Change Log"})
    print({
        "status": "PASS" if verification["exists"] and not verification["missing_sheets"] and not verification["bad_headers"] else "FAIL",
        "workbook_path": str(OUT_XLSX),
        "csv_folder_path": str(OUT_CSV_DIR),
        "sheets": verification["sheet_count"],
        "csv_count": verification["csv_count"],
        "entities": len(sheets["Entity Index"]),
        "proposed_field_rows": field_rows,
        "verification": verification,
    })


if __name__ == "__main__":
    main()
